### ISSUE TITLE
New home for this package?

### ISSUE THREAD

**Issue by ViralBShah** [JuliaGizmos/Interact.jl#104]
Is JuliaGraphics the right home for Interact and Reactive? Other thoughts?

**Comment by ViralBShah** [comment]
Or JuliaWeb perhaps?

**Comment by shashi** [comment]
I don't know where to move this to, but yes we should move it.

**Comment by tkelman** [comment]
This only really works in combination with IJulia, right? Maybe IJulia could even be its own organization. We'd have to see if @ijulia is still being used, contact github about name squatting like we did with JuliaCloud.

**Comment by ViralBShah** [comment]
I believe also in Escher.

**Comment by JobJob** [comment]
So JuliaGizmos, I'm not quite sold, don't know if it's too late but maybe JuliaUI ?

**Comment by JobJob** [comment]
Or JuliaGUI ?
Sorry I'm late to the party. Has this ship sailed?

**Comment by shashi** [comment]
I didn't really discuss this before changing the name.

Gizmo is relatively playful sounding and does not encompass all UI libraries, only just interactive embeddable widgets. I'll be moving WebDisplay and Escher in here as I make them embeddable in IJulia, Atom and other interfaces, and probably splitting up Escher into smaller packages.

The names JuliaUI and JuliaGUI both encompass a lot more than these packages; for example, Gtk, GL*, even Juno etc would fall under such an org. I don't want to rally people into moving all those packages into a common org. Besides, broader organisations tend to dilute focus.

**Comment by JobJob** [comment]
Ok good
