### ISSUE TITLE
KERNEL EXCEPTION UndefVarError: set_cur_msg not defined

### ISSUE THREAD

**Issue by dlfivefifty** [JuliaGizmos/Interact.jl#125]
Julia Version 0.5.0
Commit 3c9d753 (2016-09-19 18:14 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin15.6.0)
  CPU: Intel(R) Core(TM) i7-3820QM CPU @ 2.70GHz
  WORD_SIZE: 64
  BLAS: libgfortblas
  LAPACK: liblapack
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, ivybridge)

```julia
using Plots, Interact
@manipulate for k=1:10
    plot(1:k)
end
KERNEL EXCEPTION
UndefVarError: set_cur_msg not defined

 in handle_msg at /Users/solver/.julia/v0.5/Interact/src/IJulia/handle_msg.jl:5 [inlined]
 in (::##10#11{Interact.Slider{Int64}})(::IJulia.Msg) at /Users/solver/.julia/v0.5/Interact/src/IJulia/setup.jl:251
 in comm_msg(::ZMQ.Socket, ::IJulia.Msg) at /Users/solver/.julia/v0.5/IJulia/src/comm_manager.jl:135
 in eventloop(::ZMQ.Socket) at /Users/solver/.julia/v0.5/IJulia/src/eventloop.jl:8
 in (::IJulia.##9#15)() at ./task.jl:360
```

**Comment by JobJob** [comment]
Your Interact is on master which relies ok a change in IJulia. You need to checkout IJulia master.

**Comment by dlfivefifty** [comment]
You’re right, I checked out the tagged version and it works again

**Comment by JobJob** [comment]
Reopening this until we update the REQUIRE and tag a release.

**Comment by JobJob** [comment]
Pretty sure this is fixed now.
