### ISSUE TITLE
Widgets should read in value from "signal="?

### ISSUE THREAD

**Issue by ma-laforge** [JuliaGizmos/Interact.jl#127]
Hi,

I am using Julia v0.5, and have the following code:
```
using Interact, Reactive

fmult = Signal(Float64, 1e9) #GHz
w_fmult = togglebuttons([("kHz", 1e3), ("MHz", 1e6), ("GHz", 1e9)], value=value(fmult), signal=fmult)
display(w_fmult)
```

Issue 1) I would expect that widget `togglebuttons` initialize itself by reading the value of signal "fmult"...  but none of the widgets appear to work this way.  I often have synchronization issues between `Signals` and widgets because of this.

Issue 2) I cannot find any way to initialize the default value of `togglebuttons`.  I tried setting value="GHz" as well, but without success.

It is very possible that I am just using the wrong keyword, but I am still new to the `Interact.jl` module.

**Comment by JobJob** [comment]
Issue 2: `value_label` does the job: 
`w_fmult = togglebuttons([("kHz", 1e3), ("MHz", 1e6), ("GHz", 1e9)], value_label="GHz", signal=fmult)`

I agree that the behaviour you expect in Issue 1 seems sensible. Will look into it.

**Comment by ma-laforge** [comment]
Thanks again JobJob.

I did not see `value_label` in the "documentation".  I have similar issues with my own modules.

**Comment by JobJob** [comment]
This should also be better in my latest branch: `Pkg.checkout("Interact","jbj/widget-sig-init")`

**Comment by shashi** [comment]
closing this issue since it's now merged into master. I understand that some widgets don't support this, but let's start afresh if people want to open issues about them.
