### ISSUE TITLE
Plots: log-x sliders & interdependent values

### ISSUE THREAD

**Issue by ma-laforge** [JuliaGizmos/Interact.jl#129]
I am using Interact sliders to control parameters related to x-values on log-plots.

**Problem**
The problem is that the sliders support linear ranges, but not log ranges (because they are vectors).

**Possibilities**
 - Of course, I can use a linear ranged slider to represent `sld_logx=log(x)`, and later compute `xval=10.0^sld_logx` - but then the textbox next to the slider displays values that are not useful to the user.

 - Instead, I could create a **dependent textbox** control for `xval=10.0^sld_logx`.  This way, the user could type in x values directly (instead of log(x) values).  The problem now is keeping the original slider in sync with the new x-value without causing **infinite recursion**.

**Questions**
 - Is there a nice design pattern to deal with this kind of issue?
 - Maybe transformation functions could be added to the slider widgets to support this class of problem?

I do not really have a good solution to this problem.  Just though I would put it out there.

**Comment by JobJob** [comment]
Solution coming in #132
<img width="542" alt="screen shot 2016-12-08 at 1 35 02 am" src="https://cloud.githubusercontent.com/assets/854183/20971722/9d074990-bce6-11e6-92e9-c922a0ae49f5.png">

Will that work for your use case? It's essentially a slider that is moving an index along a vector of (precomputed) values.

**Comment by ma-laforge** [comment]
I think so - but I think it would have to be more of the form:

```
s = selection_slider(10.0.^collect(-3.0:3.0)); label="log slider")
```

(I wanted the reverse: to select x value that are spaced out at logarithmic intervals - not the logarithmic values themselves).

**Question**
What happens if the user types in a value in the text box that does not exactly match the input array?  Does the `selection_slider` find the closest entry and latch on to it?

**Comment by JobJob** [comment]
Nope, since selection sliders aren't necessarily numeric, you'll have to handle that manually with something like:
```
# This is the branch I've been working on just recently. It includes selection_slider
# and improved widget/signal sync - would be great if you can try it out

Pkg.checkout("Interact","jbj/widget-sig-init")
```
```
using Interact

#the range
exprange = map(x->2^x,1:0.01:10)

#create slider
expslide = selection_slider(exprange, label="exponential value")

#create textbox
txtbox = textbox(; label="set slider value")
nearest(arr, val) = indmin(abs(val .- arr))

#when txtbox is updated, try to parse the float, find the nearest value, and update the expslide signal with it 
map(signal(txtbox)) do txt
    val = tryparse(Float64, txt)
    if !isnull(val)
        idx = nearest(exprange,  get(val))
        push!(signal(expslide), exprange[idx])
    end
end

#display the widgets and the slider's signal's value
display.([expslide, txtbox, signal(expslide)]);
```

If you type in the box the signal and widget should update.

P.S. You can find faster ways to implement `nearest` here: https://groups.google.com/forum/#!searchin/julia-users/find$20closest$20element$20to$20a$20value$20in$20an$20array/julia-users/xBcQRebyi_o/fu4V-UtdAgAJ

**Comment by ma-laforge** [comment]
In this particular example, I believe `expslide` & `txtbox` are not in sync:

changing `txtbox` updates `explide`, but changing `expslide` does not update `txtbox`.

Indeed, this avoids the infinite recursion problem, but introduces a sync issue for the `slider/textbox` pair.

As a side note:  it appears to me that the the `nearest` behaviour that keeps the slider widget and its value in sync is what most users would want.  Why not just make it part of the `selection_slider` widget instead of requiring the user to write up all of that code for every instantiation?

**Comment by JobJob** [comment]
`Pkg.checkout("Interact","jbj/widget-sig-init")` again (I made an update to keep TextBox better in sync), oh and sorry I forgot to say earlier you also need to `Pkg.checkout("IJulia")`

Here's an updated example of how to do what you want
```
exprange = map(x->2^x,1:0.01:10)
init_val = first(exprange)

#create slider
expslide = selection_slider(exprange, label="exponential value")

#create textbox
txtbox = textbox(string(init_val); label="set slider value")
nearest(arr, val) = indmin(abs(val .- arr))

#holds the last valid float value of what's in the textbox
output_valsig = foldp(init_val, signal(txtbox)) do prev, txt
    val = tryparse(Float64, txt)
    isnull(val) ? prev : get(val)
end

#find the nearest value to what's in the textbox, and update the slider's signal with it 
map(output_valsig) do val
    idx = nearest(exprange, val)
    if value(signal(expslide)) != exprange[idx]
        push!(signal(expslide), exprange[idx])
    end
end |> preserve

#if the slider moves, update the txt box
map(signal(expslide)) do sliderval
    if nearest(exprange, value(output_valsig)) != nearest(exprange, sliderval)
        push!(signal(txtbox), string(sliderval))
    end
end |> preserve

#display the widgets and the slider's signal's value
display.([expslide, txtbox, signal(expslide), signal(txtbox), signal(output_valsig)]);
```

You avoid infinite recursion by checking the value has changed before pushing.

Regarding a default to nearest on `selection_slider`, yeah I agree it would be good, though I initially thought it might be better if those who need it implement it, because people might use selection sliders for non-numeric values. I've thought about it again and we can probably just check if the signal type is numeric. However, don't think I'll have a chance to look at that right now. Once my latest changes are merged, we should implement it.

**Comment by ma-laforge** [comment]
Thanks for the example above!

Wow - that's alot of code just to keep `txtbox` in sync with `expslide`.  I know personally would appreciate it if this behaviour was built-into `selection_slider`.

> we can probably just check if the signal type is numeric.

And/or it could be controlled by a widget parameter (available on construction?).

**Comment by ma-laforge** [comment]
**RE: `preserve`:**
Hmm....  I think that's the first time I see  `preserve` (a function?).

If I understand correctly (related to https://github.com/JuliaLang/Interact.jl/issues/128):
`preserve` would keep the signal from dissapearing the way those assigned to a variable typically do (expiring somewhere around when garbage collection happens).

Just out of curiosity: Does this mean that if the user re-runs the above code in IJulia, she will end up with zombie signal handlers accumulating in the background?

**Comment by JobJob** [comment]
Yes preserve is a function [`|>`](http://docs.julialang.org/en/release-0.5/stdlib/base/#Base.|>) is the pipe operator.

Yes it stops it from being garbage collected.

No zombies, as Shashi said elsewhere, if (all) the input signal(s) get(s) garbage collected the preserved signal will too.

**Comment by JobJob** [comment]
Ok it's down to 3 lines now if you `Pkg.checkout("Interact","master")`:

```
expslide = selection_slider(2.^(1:0.01:10), label="exponential value")
txtbox = textbox(label="entired desired value", signal=signal(expslide))
display.([expslide, txtbox, signal(expslide)]);
```
They both share the same signal.

Closing this. Re-open, or open another issue if you have more queries.

**Comment by ma-laforge** [comment]
Very cool... I never thought about it, but the resulting solution is quite simple:

You just tie in a "Signal"-ed text box, and it gets validated by the slider widget.

Very simple - almost too simple.  But: I have not yet thought of a case where this might be a nuisance - which is good.

**Comment by JobJob** [comment]
Yes, I'm almost certain there are cases where some of the auto-updating behaviour recently added will be a problem, so would like people to try it. There are some kw options to disable it which we need to document: `syncsig` for all widgets, and `syncnearest` for selection_sliders
