### ISSUE TITLE
RFC: Implications of map() syntax

### ISSUE THREAD

**Issue by ma-laforge** [JuliaGizmos/Interact.jl#133]
Hi,

I am having a bit of a struggle with the map syntax.  I am starting to understand how to use it properly... but also the reason why I find them difficult to use in more complex applications.

Take the sliders from `interact_nb/01-Introduction.ipynb` for example:

```
fx = Signal(0.0) # A float input
x = slider(0:.1:2pi, label="x")
y = map(v -> slider(-1:.05:1, value=sin(v), signal=fx, label="f(x)"), signal(x))
```

Now, if I look at the types of the `x` & `y` sliders, I get the following:

```
typeof(y)
# => Reactive.Signal{Interact.Slider{Float64}}

typeof(x) 
# => Interact.Slider{Float64}
```

That means, I need two different operations in order to extract slider value:
```
value(signal(value(y)))
value(signal(x))
```

**Proposal:**
I don't fully understand how `Interact/Reactive` succeeds at accomplishing all of its magic with so little code, but I am hoping the following pattern might work with very little changes to the architecture:

```
sldstep = slider(.01:.01:.1, label="step size")
sldmax = slider(10.0:.1:20.0, label="max value")

slddependent = slider(Float64, signal(sldstep), signal(sldmax)) do widget, vstep, vmax
	widget.range = 0:vstep:vmax
	widget.label = "dependent slider"
end
```

This way, `slddependent` would again be of type `Interact.Slider{Float64}` (not `Reactive.Signal{Interact.Slider{Float64}}`).

Also, I suppose that `Signal(slddependent)` would return a function (the one implemented above, to be exact).

**Comment by JobJob** [comment]
You need to meet `Reactive.flatten`

Here's how you can do what you want (I think):
```
sldstep = slider(.01:.01:.1, label="step size")
sldmax = slider(10.0:.1:20.0, label="max value")
slddependent_widgsig = map((vstep, vmax)-> slider(0:vstep:vmax),
                        signal(sldstep), signal(sldmax))

#Get a signal whose value is: the signal of the current widget emitted by slddependent_widgsig
slddep_value_sigsig = map(cur_slddep->signal(cur_slddep), signal(slddependent_widgsig))

#flatten signal updates both when a new widget is created (by changing sldstep or sldmax) or when the actual widget is moved
slddep_value_sig = flatten(slddep_value_sigsig)

display.([sldstep, sldmax, slddependent_widgsig, slddep_value_sigsig, slddep_value_sig])
typeof.([sldstep, sldmax, slddependent_widgsig, slddep_value_sigsig, slddep_value_sig])
```

The Signal of Signals is a bit tricky at first.

**Comment by ma-laforge** [comment]
Good to know.  I did not know about `flatten`.

My question still remains, however:

**Question**
Would it not be more natural/intuitive/simple to construct a `Signal{Function}` to update a pre-existing widget instead of creating a new widget every time one wants to change one of its properties?

(That way you could avoid complex nestings of `Signal{Widget{DataType}}`?)

**Comment by JobJob** [comment]
I'm not sure I fully understand what you are getting at, where would your `Signal{Function}` fit in, and how would it avoid the nesting?

You can modify an existing widget if you want, using foldp, or simply change slddependent_widgsig section above to:
```
widget = slider(.01:.5:15.0)
slddependent_widgsig = map(signal(sldstep), signal(sldmax)) do vstep, vmax
    widget.range = 0:vstep:vmax
    widget
end
```

That way the widget is just modified, not created afresh on every update to step or max. Though the fact you have to access `w.range` directly is perhaps not ideal from an API point of view.

**Comment by JobJob** [comment]
Oh maybe what you are looking for is:
```
sldstep = slider(.01:.01:.1, label="step size")
sldmax = slider(10.0:.1:20.0, label="max value")
s = slider(.01:.5:15.0)
update_widget(vstep, vmax) = begin
    s.range = 0:vstep:vmax
    update_view(s)
    nothing
end
map(update_widget, signal(sldstep), signal(sldmax))

display.([sldstep, sldmax, s, signal(s)]);
```

?

**Comment by ma-laforge** [comment]
Regarding your solution with:
```
slddependent_widgsig = map(signal(sldstep), signal(sldmax)) do vstep, vmax
```

I did not realize `map` could work on `Signal`s without the first argument being a function constructing a new widget (here you are just returning an existing one).  I must not have noticed those examples.

Yes.  This would indeed work for me - and is easier to wrap my head around than what I am typically used to seeing.   The only small downfall is that you end up accessing the global "widget" variable instead of a local one.  Probably not a big deal in practice.  I will have to start trying out this technique for myself!

**Comment**
I like this `map() do` syntax a bit better than what is typically used.  It allows you to add a bit more complexity to your lambda function while improving readability.

**Question**
> Though the fact you have to access w.range directly is perhaps not ideal from an API point of view.

Are you saing this because `.range` was never really meant to be accessed directly - and that assignment does not actually trigger an update in the GUI?

**Comment by ma-laforge** [comment]
Regarding your solution with:

```
update_slider(s, vstep, vmax) = begin
```

I like this solution as well.  Not sure which of the two I prefer the most.

I guess in this case, I am a bit worried that the `|> preserve` part might leave zombie signals running in the background if the user re-runs the code block.... but that's not really an essential part of the solution (I could just assign the resultant `update_slider` `Signal` to a variable in order to "preserve" it).

**Comment by shashi** [comment]
`|> preserve` will not leave zombie signals running in the background, it will also be removed ones all inputs to it disappear.

**Comment by JobJob** [comment]
Good. FYI the `do` syntax is just sugar to put the function defined in the do ... end block as the first argument to map - http://docs.julialang.org/en/release-0.5/manual/functions/#do-block-syntax-for-function-arguments

> Are you saing this because .range was never really meant to be accessed directly - and that assignment does not actually trigger an update in the GUI?

No it will work fine, it's just a minor concern that you need to access the internals of the slider, rather than via some provided mutating function which would generally be considered better style.

>  could just assign the resultant update_slider Signal to a variable in order to "preserve" it

Yep

**Comment by JobJob** [comment]
We added a `set!` function, that takes a widget, property symbol, and a signal/value. It will keep the property updated in sync with the signal.

You can do this now on master:
```
sldmin = slider(0:.01:10.0, label="min value")
sldstep = slider(0.01:.01:1, label="step size")
sldmax = slider(10.0:.1:20.0, label="max value")
sldrange = map((vmin, vstep, vmax)->vmin:vstep:vmax, 
                  signal(sldmin), signal(sldstep), signal(sldmax))
s1 = slider(.01:.5:15.0)
set!(s1, :range, sldrange)
display.([sldmin, sldstep, sldmax, s1, signal(s1)]);
```

What do you think?

**Comment by ma-laforge** [comment]
It is ok as well:  The solution allows for a more succinct solution in simple cases.

NOTE: I personally try not to use this style of function (similar to `getfield`) unless I find no other good way.  Not sure why: just for style reasons, I suppose.

Thanks for all the options.  Your examples helped significantly.

**Comment by JobJob** [comment]
Yeah, I have a some reservations about it too, but I think it's probably good to have. Python's widgets basically have this functionality built in - widgets automatically update when you set any widget property (they overload the dot operator) and I found it quite handy sometimes.

Anyway, glad I could help, should we close this?

**Comment by ma-laforge** [comment]
Sure.  Go ahead and close the issue.

It might be nice to have examples for all flavours of your solutions as a sample notebook (for documentation purposes).

I was really not aware you could do anything but construct new widgets with Interact's map() methods.

In the meantime, I have developed a few examples of my own:

https://github.com/ma-laforge/InspectDR.jl/blob/master/notebook/2_interact.ipynb

https://github.com/ma-laforge/InspectDR.jl/blob/master/notebook/3_pllstab.ipynb

**Comment by JobJob** [comment]
Nice. Are those issues in the TODOs and other comments in those notebooks still causing problems?

`map` is actually defined in Reactive, you've looked at the Reactive tutorial right? http://juliagizmos.github.io/Reactive.jl/ 

Btw if you don't want cells to display output you can add a `;` at the end of the last line of cell instead of using `nothing`.

**Comment by ma-laforge** [comment]
RE TODOs:  I believe they are all ok in master.  The reminder is mostly to update my code once Interact gets tagged.

I have not looked at the Reactive tutorial.  I will take a look at it.  Thanks.

I did not know Jupyter supported Matlab syntax for inhibiting output.  Thanks.
