### ISSUE TITLE
Jupyter hangs when using textbox(..., signal=...)

### ISSUE THREAD

**Issue by ma-laforge** [JuliaGizmos/Interact.jl#139]
Bug noticed using Julia v0.5.

I usually prefer creating my signals first (easier to set defaults, etc):
```
using Interact, Reactive
fmax = Signal(Float64, 10)
```

Now, I want to create/display a textbox for fmax:
```
txt_fmax = textbox(value(fmax), label="max freq", signal=fmax) #Will not display - notebook hangs??
display(txt_fmax) #Will hang session, for some reason
```

...But this causes my Jupyter session to hang, for some reason.

My workaround is to create the textbox *without* specifying the signal, then assigning that signal to a variable for later use:
```
txt_fmax = textbox(value(fmax), label="max freq") #This does not cause hangups
fmax = signal(txt_fmax) #Hack to get the fmax signal back from txt_fmax
display(txt_fmax)
```

I believe this to be a bug.

**Comment by JobJob** [comment]
Are you on master or the tagged version?

**Comment by ma-laforge** [comment]
Tagged versions:

Pkg.installed("Interact") = v"0.3.5"
Pkg.installed("Reactive") = v"0.3.6"

**Comment by JobJob** [comment]
If you `Pkg.checkout("Interact")` does it fix it? Seems to be working for me on master.

**Comment by JobJob** [comment]
FYI on master you can also just do `txt_fmax = textbox(label="max freq", signal=fmax)`

**Comment by ma-laforge** [comment]
Oh, sorry about that.  There is no problem on master.

I guess I just have to wait until the next update to metadata.

> FYI on master you can also just do `txt_fmax = textbox(label="max freq", signal=fmax)`

Cool, it will be nice not to have to re-specify the default value.

**Comment by JobJob** [comment]
Would be great if you can try working on the checked out Interact. There's been a fair few changes this week and things should be working better, but testing is always very welcome.

**Comment by JobJob** [comment]
Np btw with reporting a failure on the tagged version, could help others.
