### ISSUE TITLE
HTML + LaTeX does not update properly

### ISSUE THREAD

**Issue by ma-laforge** [JuliaGizmos/Interact.jl#144]
Hi,

I want to Interact to display LaTeX through `HTML()` with the following code:
```
using Interact, Reactive
wsld = slider(1e9:.1e9:10e9, label="w")
display(wsld)

map(signal(wsld)) do w
    w2=w*w; w3=w2*w
    HTML("\$\\omega=$w\\quad\\omega^2=$w2\\quad\\omega^3=$w3\$")
end
```

**Screenshot:**
![interact_html_latex](https://cloud.githubusercontent.com/assets/11205411/21279607/0ff0b738-c3af-11e6-876b-2af1ea19f0f3.png)

If I use the most recent release of Interact (v0.3.5), the initial output is displayed correctly, but when I move the slider, Interact displays the HTML code instead of the formatted output.

If I checkout "master", the initial output is again displayed correctly, and never changes as I move the slider.

It would be nice if Interact supported LaTeX outputs through `HTML()`.

**Comment by JobJob** [comment]
Try the `latex` widget in place of `HTML`

**Comment by ma-laforge** [comment]
I get the same problem (at least very similar) with `latex` as with `HTML`.  Again, the problem persists on master.

**Comment by JobJob** [comment]
This pretty much works for me:

![latex_slider2](https://cloud.githubusercontent.com/assets/854183/21301037/d15555c8-c5fd-11e6-83c0-8fb041513cdc.gif)

If you open a new python notebook and run:
```
import ipywidgets
ipywidgets.__version__
```
What does it show?

**Comment by ma-laforge** [comment]
My version: v5.2.2.

NOTE: I am testing this in a virtual machine running Linux.

Other observation:
If I remotely access my notebook server (running on Linux) from a Windows/firefox session, all reactive communication is broken when I update to Interact/master (even when updating simple text)...  But things work fine when I revert to the latest tagged version of Interact.

**Comment by ma-laforge** [comment]
I typically run with Juila v0.5, but I decided to run other tests given how well it works for you.

I ran this code in a JuliaBox session, so we can have a common configuration.

I ran on Julia v0.5 & Julia v0.6 (dev).  Neither will update the latex output (and Interact/master won't even display it the first time.

**Comment by JobJob** [comment]
Ok thanks very much for that info. Slightly concerning 😱 

Is it possible it's not working when accessing from Windows/Firefox on master because IJulia is not on master? I'm assuming that's the issue (#125) on JuliaBox (I couldn't get it to checkout or clone IJulia master and not die). Are there errors in the linux terminal that runs Jupyter/IJulia? Or in the browser console?

I was only on Julia 0.5 on macOS. `latex` mostly works for me there (with IJulia master, Interact master) in Chrome/Firefox. There is a brief period of time after moving the slider when either the raw Latex string shows or the equations appear in small font, before it displays normally.

**Comment by ma-laforge** [comment]
There are no errors in my Linux terminal, but yes:

Checking out IJulia/master does re-establish communication.  Thanks.

Also, my `latex()` output now updates.  But now, I too have this odd behaviour where the equation shows up in small font, then displays normally, then small font, then normal, then...  Just like you described.

**Comment by JobJob** [comment]
Yeah I think that's an issue with math typesetting in the browser (mathjax?) or ipywidgets itself. This has the same issue in python:
```
import ipywidgets as widgets
from IPython.display import display
import time
lbl = widgets.Label(value=r'$\frac{1}{2}$')
display(lbl)
for i in xrange(10):
    time.sleep(0.5)
    lbl.value = "$\\omega="+str(i)+"\\quad\\omega^2$"
```
If you manage to find a workaround in python - e.g. possibly setting some layout properties of the widgets - we could look into it further.

**Comment by JobJob** [comment]
Your original version should work nicely if you 
```
Pkg.update("Interact")
Pkg.add("LaTeXStrings")
```
then replace `HTML` with `latexstring`
and disable fast preview: right click on the MathJax output, then Math settings->Math renderer->fast preview (uncheck it)
