### ISSUE TITLE
I HAVE NO IDEA WHAT THIS MEANS

### ISSUE THREAD

**Issue by Rezoseansstudios** [JuliaGizmos/Interact.jl#145]
libfunc_require:(12,1-44): module 'randomvoice' not found <-----------WHAT DOES IT MEAN

**Comment by JobJob** [comment]
Excellent question - how did you manage to produce this error - can you post reproduction steps?

**Comment by Rezoseansstudios** [comment]
i opened unitale and added a mod in the mods file called gaster and when i play unitale i click on it and it gives me libfunc_require:(12,1-44): module 'randomvoice' not found

**Comment by shashi** [comment]
> i opened unitale and added a mod in the mods file called gaster and when i play unitale i click on it and it gives me libfunc_require:(12,1-44): module 'randomvoice' not found

...I have no idea what this means!

Are you sure you opened the issue on the right github repo? :)

**Comment by Rezoseansstudios** [comment]
IT'S NOT ON GITHUB. ITS ON MY PC

**Comment by Rezoseansstudios** [comment]
![tumblr_inline_nuls3cvxsa1si73t5_500](https://cloud.githubusercontent.com/assets/24687503/21583873/538e7e3a-d061-11e6-8909-bed0c2c5ae8e.gif)

**Comment by Rezoseansstudios** [comment]
![tumblr_inline_nuls3cvxsa1si73t5_500](https://cloud.githubusercontent.com/assets/24687503/21583876/5d7b38d4-d061-11e6-87e4-2e1523bc128e.gif)
![tumblr_inline_nuls3cvxsa1si73t5_500](https://cloud.githubusercontent.com/assets/24687503/21583877/6549fdca-d061-11e6-9261-e64ec63d39c6.gif)
![tumblr_inline_nuls3cvxsa1si73t5_500](https://cloud.githubusercontent.com/assets/24687503/21583878/675fe0e8-d061-11e6-92fe-f1b68e2e14e4.gif)
