### ISSUE TITLE
SymPy output not interactive? (Julia 0.5)

### ISSUE THREAD

**Issue by bradleyashton** [JuliaGizmos/Interact.jl#146]
If I do the following (using a nice example I saw introducing interact)

```
using SymPy

x=Sym("x")
@manipulate for n=1:50
    SymPy.diff(sin(x^2),x,n)
end
```

The rendering doesn't work, except for the default output (at the middle of the slider), which correctly renders (mathJax?) output into a nicely formatted equation. If I move the slider, the SymPy.diff command seems to still be processed correctly, but now the output is (say for n=1):

`$$2 x \cos{\left (x^{2} \right )}$$`

Any suggestions as to how to fully enable interactive output and have it render?

Many thanks

```
julia> versioninfo()
Julia Version 0.5.0
Commit 3c9d753 (2016-09-19 18:14 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) M-5Y51 CPU @ 1.10GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, broadwell)
```

**Comment by JobJob** [comment]
Hi, thanks for the detailed report. I'm not exactly sure why MathJax isn't rendering the updated latex string. I wanted to give you a simple workaround but unfortunately I discovered it doesn't work inside `@manipulate` blocks atm (see #147 - `latex` in the below is a type of widget). In the meantime, here is a partial workaround, that essentially unpacks the `@manipulate` and wraps the equation in the `latex` display widget:
```
x = Sym("x")
n = slider(1:50)
eqn_signal = map(nv->latex(SymPy.diff(sin(x^2),x,nv)), signal(n))
display.([n, eqn_signal]);
```
I still have the following issues with that workaround:
1) On first run it shows `[Math Processing Error]` for me. It goes away if you move the slider or re-run the cell. Do you get the same?
2) With long equations it stretches off the end of the page for me. This doesn't seem to happen e.g. with `SymPy.diff(sin(x^2),x,24)`. Seems to be a separate issue with the `latex` display widget - I get the same problem with `latex(SymPy.diff(sin(x^2),x,24))`

**Comment by bradleyashton** [comment]
Thanks a lot for this workaround. It is interesting to see how to unpack @manipulate. I get exactly the same issues you report above.

**Comment by JobJob** [comment]
Your original version should work if you `Pkg.update("Interact")`.

Also, I like the look of it better when you disable fast preview: right click on the MathJax output, then Math settings->Math renderer->fast preview

Aside: for general latex output, outside of SymPy, I recommend using [LaTeXStrings](https://github.com/stevengj/LaTeXStrings.jl) instead of the `latex` widget I suggested in my workaround, it should display/update better.
