### ISSUE TITLE
`@manipulate` doesn't work when the block returns a Widget

### ISSUE THREAD

**Issue by JobJob** [JuliaGizmos/Interact.jl#147]
```
@manipulate for i in [1:10;]
    slider(i:i+3)
end
```

Outputs nothing. This is because:
1) manipulate's signal is of `typ=Any` (so `Signal{Widget}` display handling doesn't kick in)
2) widget display happens in `metadata` not `show`. If it happened in `show` choosing a new option would just create lots of sliders, not replace them

Possible solution:
Allow explicitly adding a type to the manipulate expression, e.g. 
a)
```
@manipulate for i in [1:10;], typ=Widget
    slider(i:i+3)
end
```
b) my preference
```
@manipulate for i in [1:10;]
    slider(i:i+3)
end::Widget
```

**Comment by JobJob** [comment]
Could also use some other symbol like `-->` in b) since the `@manipulate` returns a signal of that type, so it's potentially confusing that this is not true:
```
(@manipulate for i in [1:10;]
    slider(i:i+3)
end)::Widget
```

**Comment by piever** [comment]
Closing as
```julia
@manipulate for i in [1:10;]
    slider(i:i+3)
end
```

works as expected in the latest (unreleased) Interact.
