### ISSUE TITLE
Main Interact demo broken

### ISSUE THREAD

**Issue by jheinen** [JuliaGizmos/Interact.jl#150]
The main demo in `README.md` is broken with v0.4.0. Same for some of my `GR.jl` demos ...

```julia
using Interact
using Gadfly
@manipulate for Φ=0:π/16:4π, f=[:sin => sin, :cos => cos]
    plot(θ -> f(θ+Φ ), 0, 25)
end
```
**MethodError: objects of type Pair{Symbol,Base.#sin} are not callable**

Any idea?

**Comment by JobJob** [comment]
Oh nice :) 
I have a quick fix for this if you `Pkg.checkout("Interact", "jbj/option-pairs")`
What's the equivalent in GR to the above? Also can you post here some of the cases in GR that don't work?

I really like GR btw - it's very fast!

**Comment by jheinen** [comment]
@JobJob : Thanks a lot - this works:

```julia
using Interact
using GR
inline()
@manipulate for Φ=0:π/16:4π, f=Dict(:sin => sin, :cos => cos)
    θ = linspace(0, 25, 100)
    plot(θ, θ -> f(θ+Φ ))
end
```

Please merge the PR :-)
