### ISSUE TITLE
@manipulate defaults to 1 less than the median value for ranges of odd length

### ISSUE THREAD

**Issue by rdeits** [JuliaGizmos/Interact.jl#153]
This behavior seems to have crept in with 05bbfc0d5441588f3c75d9f28c0891b675f36c1b (from git-bisect). Previously, doing 

```julia
@manipulate for i in linspace(-1, 1, 11)
```

would default to `i = 0.0` (which makes sense). Now it defaults to `i = -0.2`. 

I'm happy to attempt a fix if this is indeed not the intended behavior.

**Comment by JobJob** [comment]
Oopsie, sorry and thanks for that, fixed on master.

Saw you have a cryptic crossword solver - nice, I like doing the cryptic.

**Comment by rdeits** [comment]
Thanks! 

And yeah--I enjoyed cryptics enough that I ended up making myself obsolete :wink:. It would be fun to port it to Julia someday...

**Comment by JobJob** [comment]
Ha :+1:
