### ISSUE TITLE
"preserve not defined" when using Interact outside of ipython notebook

### ISSUE THREAD

**Issue by tawheeler** [JuliaGizmos/Interact.jl#156]
The following code, when executed in the terminal, throws an error:

```
using Interact
@manipulate for x in 1 : 3
       x
end
```

```
Interact.Options{:SelectionSlider,Int64}(Signal{Int64}(2, nactions=1),"x",2,"2",Interact.OptionDict(DataStructures.OrderedDict("1"=>1,"2"=>2,"3"=>3),Dict(2=>"2",3=>"3",1=>"1")),Any[],Any[],true,"horizontal")
ERROR: UndefVarError: preserve not defined
```

I understand that one typically runs this in a Julia IPython notebook, but I am trying to automate tests by using NBInclude. This errors is causing my tests to fail.

**Comment by shashi** [comment]
Are you using the master branch of Reactive?

**Comment by tawheeler** [comment]
Thank you for the response. Running `Pkg.checkout("Reactive")` did not solve the problem.

**Comment by JobJob** [comment]
Change the first line to `using Interact, Reactive`

`using Reactive` is only called in the Main module when Interact/src/IJulia/setup.jl gets included, which doesn't happen if the user is not in IJulia.

**Comment by tawheeler** [comment]
That worked! Thank you!

**Comment by shashi** [comment]
No I meant you should not be using the master branch :)
