### ISSUE TITLE
Fix Slider Signal string Test

### ISSUE THREAD

**Issue by JobJob** [JuliaGizmos/Interact.jl#162]
Reactive changed the way signals are displayed, which broke this test: https://github.com/JuliaGizmos/Interact.jl/blob/master/test/ijulia.jl#L25

caught in: https://github.com/JuliaLang/METADATA.jl/pull/8931

When https://github.com/JuliaGizmos/Reactive.jl/pull/129 gets merged we'll fix the test.

**Comment by tkelman** [comment]
can we please fix this without requiring a complete rewrite of the package?

**Comment by shashi** [comment]
I believe  JuliaGizmos/Reactive.jl#129 also changes the printing.

**Comment by JobJob** [comment]
Exactly, that pr also changes the printing, so the test would break again after that gets merged, I see now that wasn't clear above.

It will be merged in the next week I would think.

**Comment by shashi** [comment]
:+1: :vulcan_salute:
