### ISSUE TITLE
Way to clear console to allow println inside @manipulate

### ISSUE THREAD

**Issue by djsegal** [JuliaGizmos/Interact.jl#165]
Right now if you `println(...)`, the output keeps getting added to the Jupyter cell.

Is there a way to clear that output at the beginning of each `@manipulate` loop?

**Comment by djsegal** [comment]
Fixed by: 

+ `IJulia.clear_output(true)`

More details: [here](https://discourse.julialang.org/t/way-to-programmatically-clear-last-println-statement-in-jupyter-cell/3582/2)

**Comment by JobJob** [comment]
Nice. If you return the string from the manipulate like so
```
@manipulate for foo=["a","b","c"]
    foo
end
```
the value displayed will update it as you press the toggle buttons. Unfortunately, manipulate doesn't support returning multiple values, so you can't return e.g. a tuple of a string and some other value (like a plot) and have them both update.

Will hopefully address this in the next few months, crossref: https://github.com/JuliaGizmos/Interact.jl/pull/143

**Comment by rand5** [comment]
I am running into an instance where a call to `IJulia.clear_output(true)` will clear the widgets. Is this the intended behavior? Doesn't seem to do this in a reliable manner.
