### ISSUE TITLE
Strange issue with Interact+PyPlot.. just with a semicolon!

### ISSUE THREAD

**Issue by mgiugliano** [JuliaGizmos/Interact.jl#168]
Just adding a single semicolon (!) to the following (working) code in a Jupyter notebook:

`using PyPlot, Interact

fig = figure("Test")
@manipulate for a=0:0.01:1; withfig(fig) do
    x = 0:0.01:2π
    y = sin(x*a)
    plot(x,y, "k-")    # Never dare adding a semicolon here
    end
end`

as in 

`using PyPlot, Interact

fig = figure("Test")
@manipulate for a=0:0.01:1; withfig(fig) do
    x = 0:0.01:2π
    y = sin(x*a)
    plot(x,y, "k-");    # Never dare adding a semicolon here
    end
end`

is sufficient to break the expected behaviour: the slider appears but not so the plot.
This strange behaviour came as I upgraded to the most recent versions of Julia, Interact, PyPlot, etc.
It also happens under different circumstances I am unable to distill or dissect.

macOS (x86_64-apple-darwin13.4.0)
Julia Version 0.5.2
IJulia 1.5.0
Interact 0.4.5
PyPlot    2.3.2
PyCall 1.12.0
Python 3.6              (installed by Anaconda 4.3.1)
Jupyter 4.2.1           (installed by Anaconda 4.3.1)
ipywidgets 5.2.2     (installed by Anaconda 4.3.1)

**Comment by JobJob** [comment]
Hi,

A semi-colon at the end of a cell suppresses output. This case shouldn't be suppressed and isn't on 0.6, but seems to be on 0.5. I think this is the issue https://github.com/JuliaLang/julia/issues/19296 which is now resolved.

At the REPL on 0.5 (IJulia's behaviour matches the REPL) output is suppressed with this:
```
begin 
    a = 1; #i see
end
```
It's not suppressed without the comment, so
`plot(x,y, "k-");` works in the above on 0.5

Anyway this all works better on 0.6 but it's not an Interact issue. 

Cheers nonetheless.

**Comment by mgiugliano** [comment]
Thank you JobJob. That was however not the case with PyPlot only (i.e. without Interact).
For instance, the code 

using PyPlot
plot(1:10,1:10);

works with or without the semicolon.

**Comment by JobJob** [comment]
Oh yes, I forgot to clarify that above. It's the `withfig` that makes all the difference. 

`PyPlot.plot` displays the plot as a side-effect. However, when called within a `withfig(fig)` block, it doesn't display in the notebook (I guess it writes it to `fig` instead), and the `Figure` returned/modified by withfig (i.e. `fig` in your example) is only displayed if it is the result of the cell (or if you call `display(fig)` explicitly).

e.g.
```
using PyPlot
fig = figure("Test")
withfig(fig) do
    plot(1:10,1:10)
end;
```
Will not display anything, but if you remove the semicolon at the end, it'll display the plot/figure`fig` as the result of the cell.

Definitely a little subtle, especially with the semi-colon suppressing output from within a two nested blocks on 0.5!
