### ISSUE TITLE
manipulate shows multiple images rather than a single image

### ISSUE THREAD

**Issue by cormullion** [JuliaGizmos/Interact.jl#171]
Hi @shashi! I'd love to get Interact working with my little graphics package [Luxor](https://github.com/JuliaGraphics/Luxor.jl). It _nearly_ works, so I think it might be possible to get it working correctly, but I don't know enough about IJulia/Interact to know what needs to be done.

The problem is that the different images produced are shown separately, rather than replacing each other:

```
using Luxor, Interact
@manipulate for i in 50:5:100
    Drawing(250, 250)
    origin()
    background("white")
    sethue("black")
    hypotrochoid(100, i, 50, :stroke)
    finish()
    preview()
end
```

![screen shot 2017-07-09 at 12 12 33](https://user-images.githubusercontent.com/52289/27993297-f176bef0-649f-11e7-879e-88cb2437bc0d.png)

Any clues as to how I can fix/adapt my code?

**Comment by JobJob** [comment]
looks cool, try adding `IJulia.clear_output(wait=true)`

**Comment by cormullion** [comment]
@JobJob Brilliant! That seems to work, thanks!

**Comment by shashi** [comment]
That's a cool! demo :-)

**Comment by JobJob** [comment]
Modifying all the parameters is fun 😄 
```
using Luxor, Interact
@manipulate for R in 1:100, r in 50:0.1:100, d in 1:100
    IJulia.clear_output(true)
    Drawing(250, 250)
    origin()
    background("white")
    sethue("black")
    hypotrochoid(R, r, d, :stroke)
    finish()
    preview()
end
```

**Comment by cormullion** [comment]
@JobJob Nice, and it doesn't seem to crash! (Although that `0.1` step reveals some interesting glitches! 😀)
