### ISSUE TITLE
Unintentional Button Evaluation

### ISSUE THREAD

**Issue by rand5** [JuliaGizmos/Interact.jl#172]
I am working with the following minimal example in an IJulia notebook:
`B = button("Click Me")`
`map(display,[B])`
`map(v->  println("Hello World"),signal(B));`

When I put this into a single cell in a notebook and execute it, I see (1) the button, (2) "Hello World". It seems as if the function within `map` is being evaluated once before the button is clicked for the first time. Is there a way to keep this from happening?

**Comment by JobJob** [comment]
yep `map(v-> println("Hello World"),signal(B), init=nothing)`

**Comment by rand5** [comment]
Brilliant
