### ISSUE TITLE
Allow default values in sliders

### ISSUE THREAD

**Issue by djsegal** [JuliaGizmos/Interact.jl#174]
Is there a way to circumvent having to use the middle value of the slider?

**Comment by JobJob** [comment]
`slider(1:10; value=2)`

**Comment by djsegal** [comment]
can you do that in a `@manipulate` loop?

**Comment by JobJob** [comment]
```
using Interact
@manipulate for a in slider(1:10, value=2)
    a
end
```

**Comment by djsegal** [comment]
Assuming you know this already, but:

+ this doesn't show the label to the left of the slider then

**Comment by JobJob** [comment]
`label=a`

**Comment by JobJob** [comment]
Is none of that in the docstring for slider? Not at comp

**Comment by djsegal** [comment]
Damn, yea.

I just didn't know how to find it before. I guess I should have checked the docstring first
