### ISSUE TITLE
No widgets displayed after upgrading/installing ipywidgets 7.x

### ISSUE THREAD

**Issue by kdheepak** [JuliaGizmos/Interact.jl#176]
I get the following error message in Chrome, and no widgets show up.

```javascript
manager-base.js:127 Wrong widget protocol version: received protocol version '', but was expecting major version '2' ManagerBase.handle_comm_open @ manager-base.js:127
```

**Comment by jheinen** [comment]
We have the same problem. Replacing the JS code with the old version (`../lib/python2.7/site-packages/widgetsnbextension-2.0.0-py2.7.egg/share/jupyter/nbextensions/jupyter-js-widgets/`) fixes the problem, bit this can only be considered as an ugly hack.

**Comment by JobJob** [comment]
The latest Ipywidgets, version 7, is not supported by Interact.jl at this time.
You can check your ipywidgets version by opening a Python notebook and running
```
import ipywidgets
ipywidgets.__version__
```
you can downgrade your ipywidgets version at the terminal (assuming you installed ipywidgets with pip:
```
(sudo) pip install ipywidgets==6.0.0
```
you may need to replace `pip` with `pip2` or `pip3` depending on which python version you are using, and pip is configured with.

Aside: the console message can be ignored

**Comment by kdheepak** [comment]
Thanks for the replies. Are there plans to support v7? It would be great if that were possible. Perhaps some of the ipywidgets devs may be able to share their thoughts on what changes were made and a possible upgrade path could be laid out.

**Comment by JobJob** [comment]
>  Are there plans to support v7? ... Perhaps some of the ipywidgets devs may be able to share their thoughts on what changes were made and a possible upgrade path could be laid out.

Yes I would think we would definitely want to support the latest version. I'd be happy to advise where to look in the Interact code if you want to take a look. And yes, would be good to get some info from the ipy devs.

> It would be great if that were possible

Out of curiosity, are there any new features you're excited about in v7?

@djsegal, I see that one of the changes for ipywidgets v7 is that widgets are now displayed in the regular output area, not in their own special widget area. Not 100% sure but this may mean #164 would just work if we upgraded. So supporting v7 could be a good path forward on that. Don't shoot me if it doesn't work though :)

**Comment by kdheepak** [comment]
We have been building widgets and extensions on those widgets using v7, and some of the changes in v7 are not backward compatible. It would be great to use Interact.jl with those widgets. I'd like to look into this if you could point me in the right direction.

**Comment by JobJob** [comment]
There were just a couple of minor changes, preliminary support available if you `Pkg.checkout("Interact","jb/ipywidg7")` you'll also need to add this diff to IJulia/src/comm_manager.jl

```
--- a/src/comm_manager.jl
+++ b/src/comm_manager.jl
@@ -32,13 +32,14 @@ function Comm(target,
               primary=true,
               on_msg=noop_callback,
               on_close=noop_callback;
-              data=Dict())
+              data=Dict(),
+              metadata=Dict())
     comm = Comm{Symbol(target)}(id, primary, on_msg, on_close)
     if primary
         # Request a secondary object be created at the front end
         send_ipython(IJulia.publish[],
                      msg_comm(comm, IJulia.execute_msg, "comm_open",
-                              data, target_name=string(target)))
+                              data, metadata, target_name=string(target)))
```

Let me know how it goes.

**Comment by kdheepak** [comment]
Wow that's great! Thanks for the fix, I was able to test simple example and get them to work. I'm still trying to understand a lot of stuff, where and why one would use `Signal{Widget}` for example, so I'm not sure I'll run into that just yet. If I do, do you recommend I open a new issue? Why do you think it will not work with anything complicated?

**Comment by JobJob** [comment]
`chooser` below is an example of a Signal{Widget} it's a signal whose value is a Widget. Choosing a different widget type (dropdown, slider, or toggle buttons) changes `signal(widget_choice)`'s value which then causes `chooser` to hold a different widget to choose from (a,b,c,z). This works with master Interact on Ipywidgets <= v6.0.0
```
using Interact, DataStructures

widget_choice = togglebuttons(OrderedDict(
    "dropdown"=>dropdown, 
    "slider"=>selection_slider, 
    "toggle buttons"=>togglebuttons))
choices = ["a", "b", "c", "z"]
chooser = map(w->w(choices), signal(widget_choice); typ=InputWidget)
display.([widget_choice, chooser]);
```

<img width="529" alt="signal_widget" src="https://user-images.githubusercontent.com/854183/30004566-4d1ad07e-9115-11e7-8d69-3c57a2f82793.png">

This may not be too hard to fix for ipywidgets 7.0, if anyone is interested in taking a look, the crux of the code for Signal{Widget} display is [here](https://github.com/JuliaGizmos/Interact.jl/blob/jb/ipywidg7/src/IJulia/setup.jl#L304-L315) and updating [here](https://github.com/JuliaGizmos/Interact.jl/blob/master/src/IJulia/setup.jl#L198-L222), you probably just need to undisplay the widget in remove_view - check the changes to `display_widget` in this commit to see how display of widgets is now done (https://github.com/JuliaGizmos/Interact.jl/commit/03f681c1bc35074f88231a63dfe60dab0bb9a974), you'll probably need to use an update_display_data message - http://jupyter-client.readthedocs.io/en/latest/messaging.html#update-display-data

**Comment by jasongrout** [comment]
And we're happy to advise in the migration. Let us know if you have any questions!

**Comment by JobJob** [comment]
Cheers @jasongrout! Will hit you up if we have some more questions.

This should be fixed now with a `Pkg.update()` (both Interact.jl and IJulia.jl need to be updated)

**Comment by jheinen** [comment]
Thanks a lot! Everything is working again ...
