### ISSUE TITLE
Some glitchiness/delays/stalls in @manipulate

### ISSUE THREAD

**Issue by cormullion** [JuliaGizmos/Interact.jl#177]
Running code like this:

```
using Luxor, Interact
@manipulate for R in 1:100, r in 50:100, d in 1:100
    @png begin
        setline(0.2)
        hypotrochoid(R, r, d, :stroke)
        text("$R $r $d", 0, 150)
    end 300 300
end
```

usually works well (I got it working thanks to you guys!), but there are times when the sliders stop responding. I attribute this usually to my fairly slow Mac (mid-2011 iMac with 2.7 GHz Intel Core i5). Also, I usually use Safari, which might not be the fastest. If it does stall, it sometimes restarts, but sometimes the call needs evaluating again.

`@svg` instead of `@png` may make the system sweat a bit more... :)

(Julia v0.6, Interact v0.5.0, IJulia v1.6.0)

**Comment by barche** [comment]
I get the same, using:

```julia
using Interact
using Luxor

@manipulate for θ in 0:360
    @svg begin
        arc(0,0,50,0,θ/180*π,:stroke)
    end 300 300
end
```

Tested on Linux (firefox) and Mac (safari), re-evaluating the cell makes it work again.

**Comment by cormullion** [comment]
@barche I can't make yours go wrong — yet! Unlike my example, the SVG file is very small, which suggests that it's not the file size...

**Comment by JobJob** [comment]
I can reproduce with
```
@manipulate for R in 1:500, r in 50:500, d in 1:500
    @png begin
        setline(0.2)
        hypotrochoid(R, r, d, :stroke)
        text("$R $r $d", 0, 150)
    end 900 900
end
```
Then move the r,d sliders fast just after moving the R slider, while it's still updating. The R slider stops working. Not sure what's going on, but possibly some IO truncation. Do you ever see this error:
```
IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`
```
?

**Comment by cormullion** [comment]
I saw that error [once or twice](https://github.com/JuliaLang/IJulia.jl/issues/534), but I think it got fixed in an IJulia upgrade...

**Comment by barche** [comment]
@JobJob I'm not seeing that error, where would it appear? I started Jupyter using `jupyter notebook` and I see the normal NotebookApp log in the terminal, but this error never appears.
