### ISSUE TITLE
widgets not displayed after update

### ISSUE THREAD

**Issue by korsbo** [JuliaGizmos/Interact.jl#178]
Hi, 
I just ran a Pkg.update() which got me Interact 0.6.0 (along with a few other updates, notably IJulia). However, after this, the widgets are no longer displayed.

```
using Interact
s = slider(1:10)
display(s)
```
Does not return, nor display, anything in Jupiter. 
Code which previously worked now fails to display the widgets. 

I was initially running ipywidgets 5.2.2, but after reading #176 I installed 6.0.0. This did however not have any effect. I have also restarted jupyter, and even my computer, to no avail.

**Comment by shashi** [comment]
I was hoping it would continue to work with ipywidgets 5.2.2... Do you see any output / warnings when you run Pkg.build("Interact") ?

**Comment by korsbo** [comment]
I have now upgraded to ipywidgets 6.0.0, but this is by build output:
<img width="626" alt="screen shot 2017-09-15 at 19 00 22" src="https://user-images.githubusercontent.com/16306680/30496749-4d98a59e-9a48-11e7-9768-2016c74a5c87.png">

**Comment by juliohm** [comment]
I can confirm the issue on my machine as well.

**Comment by korsbo** [comment]
I got it to mostly work again by installing ipywidgets 7.0.1:
```
pip install ipywidgets==7.0.1
```

However, the selection widget will still not display with the multi=true option.

**Comment by JobJob** [comment]
This should be fixed if you `Pkg.update()` (make sure `Pkg.build()` gets run after you down/upgrade your Ipywidgets version).

Can you open a separate issue for the selection widget with the multi=true option?
