### ISSUE TITLE
Selection not displayed if multi=true

### ISSUE THREAD

**Issue by korsbo** [JuliaGizmos/Interact.jl#179]
After a recent update the selection widget stopped being displayed when it has the keyword argument multi=true.
<img width="331" alt="screen shot 2017-09-17 at 15 13 23" src="https://user-images.githubusercontent.com/16306680/30521648-d87fa5a4-9bba-11e7-9040-d0140c31ccde.png">

**Comment by JobJob** [comment]
Try `Pkg.checkout("Interact", "jb/selmulti-ipyw7")` - if you can check I haven't broken other selection widgets or when `mutli != true` - it would be great

**Comment by korsbo** [comment]
When I run `Pkg.checkout("Interact", "jb/selmulti-ipyw7")` i get:
<img width="1116" alt="screen shot 2017-09-17 at 16 25 30" src="https://user-images.githubusercontent.com/16306680/30522267-22da2cdc-9bc5-11e7-950c-2c15784fb17b.png">

running the same cell again yields:
<img width="1116" alt="screen shot 2017-09-17 at 16 27 59" src="https://user-images.githubusercontent.com/16306680/30522276-563b0bdc-9bc5-11e7-9b1d-f92348e1031e.png">

I have tried with re-installing Interact, is there anything else that I should do?

**Comment by JobJob** [comment]
do you have changes to your local copy of Interact?

**Comment by JobJob** [comment]
the basic idea is to checkout the `jb/selmulti-ipyw7` branch. 
So cd to ~/.julia/v0.6/Interact (`Pkg.dir("Interact")`)
then 
```
git fetch
git checkout jb/selmulti-ipyw7
```

**Comment by JobJob** [comment]
or possibly
```
git fetch origin
git checkout -b jb/selmulti-ipyw7 origin/jb/selmulti-ipyw7
```

**Comment by korsbo** [comment]
The package manager did not seem to like me, but Git never fails.

It now works as expected with or without multi=true. 
I also tested radiobuttons, dropdown and togglebuttons, they all work fine.
Thanks!

**Comment by korsbo** [comment]
After some more testing I found that selection is no longer happy when you try to set a default value and you use multi=true.

<img width="1099" alt="screen shot 2017-09-17 at 17 07 38" src="https://user-images.githubusercontent.com/16306680/30522612-ee96c65a-9bca-11e7-88a9-d29f08b6bde2.png">

**Comment by JobJob** [comment]
Thanks for that!
can you post the code? typing is hard :)

**Comment by korsbo** [comment]
```
s = selection([:x, :y], multi=true, value=[:y])
display(s)
signal(s)
```

**Comment by JobJob** [comment]
Definitely a bug. Needs a little care to fix, I'm guessing this would've happened even on previous versions (i.e. don't think this is related to recent changes) - had you ever tried that before?

**Comment by korsbo** [comment]
It has worked before, but I have never tried to give it an array with more than one element.

**Comment by korsbo** [comment]
Previously it used the value=... correctly for the signal output, but not for the graphical highlighting of the option in the widget.

**Comment by korsbo** [comment]
I ran into a new and probably related bug.

I think that you may have hard-coded some variable name `s` somewhere.
<img width="715" alt="screen shot 2017-09-17 at 17 53 09" src="https://user-images.githubusercontent.com/16306680/30523014-567ca40a-9bd1-11e7-9d76-c6e067a46819.png">

You should be able to reproduce the bug if you restart the kernel. If you have already defined `s` with the previous code that we used you will not get the same issue.

**Comment by korsbo** [comment]
I looked through your PR and found:
```
idxs2keys(x::Interact.OptionDict, indexes) = collect(keys(s.options))[indexes .+ 1]
```
The s.options looks suspicious to me.
I also made a comment in the PR, so you should find the line easily.

**Comment by JobJob** [comment]
Ok cheers for all that. I now see there *was* (to my surprise) some update to a related section of code recently.

> Previously it used the value=... correctly for the signal output, but not for the graphical highlighting of the option in the widget.

Behaviour should now be as before. The auto-highlighting is still broken for multi-select. If you want to have a go at fixing it, there's a [comment here](https://github.com/JuliaGizmos/Interact.jl/blob/master/src/widgets.jl#L333-L338) that gives you some pointers. 

I think you can ignore the idea there about the type parameters: "so would want to have Tvalue and Tlabel type parameters", I'm not sure exactly what I was getting at, and if you need them, they are available anyway as `keytype/valtype(ow.options)`

Thanks very much for your help here.
