### ISSUE TITLE
@manipulate stopped working

### ISSUE THREAD

**Issue by AshtonSBradley** [JuliaGizmos/Interact.jl#183]
Seems to have stopped working in any context. Julia 0.6.0. Doesn't throw an error,  just throws out a default value of the slider, and the slider doesn't show up.

**Comment by JobJob** [comment]
Try 
```
Pkg.checkout("Interact")
Pkg.build("Interact")
```

A new version should be tagged shortly

**Comment by JobJob** [comment]
Also what's the output when you run this from the terminal:
`python -c 'import ipywidgets; print(ipywidgets.__version__)'`

possibly replace python with python2 or python3, depending on which you use to run IJulia/jupyter notebook

**Comment by AshtonSBradley** [comment]
```terminal
grok:~ abradley$ python -c 'import ipywidgets; print(ipywidgets.__version__)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named ipywidgets
grok:~ abradley$ python2 -c 'import ipywidgets; print(ipywidgets.__version__)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named ipywidgets
grok:~ abradley$ python3 -c 'import ipywidgets; print(ipywidgets.__version__)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'ipywidgets'
```

**Comment by JobJob** [comment]
fascinating. 
Try open a python notebook (python2 or 3 kernel) and do 
```
import ipywidgets
print(ipywidgets.__version__)
```
What OS are you on? do you install python packages with pip or conda or ?

**Comment by JobJob** [comment]
Also create a file called `(path to Interact)/deps/ipywidgets_version` and save `6.0.0` in it, restart julia, let me know your results

**Comment by AshtonSBradley** [comment]
```julia
julia> versioninfo()
Julia Version 0.6.0
Commit 903644385b (2017-06-19 13:05 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, skylake)
```

**Comment by AshtonSBradley** [comment]
I think the master branch has solved it now, thanks a lot!!

**Comment by juliohm** [comment]
The master branch is not working for me:

```julia
Julia Version 0.6.1-pre.0
Commit dcf39a1dda* (2017-06-19 13:06 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, skylake)
```
Chromium Version 61.0.3163.91 (Developer Build) (64-bit)

**Comment by JobJob** [comment]
The workaround for now is to create a file (path to Interact)/deps/ipywidgets_version and save 6.0.0 in it, if you have IPywidgets version >= 7.0.0 it should probably work straight away (though if that file exists, save 7.0.0 in it). Then restart the IJulia kernel (and possibly refresh the browser window).

Hopefully soon we'll have a more reliable way to test for IPywidgets version, and use the appropriate widgets protocol.
