### ISSUE TITLE
ijulia setup.jl should probably make explicit call to Reactive/Interact.preserve

### ISSUE THREAD

**Issue by JobJob** [JuliaGizmos/Interact.jl#186]
this line: https://github.com/JuliaGizmos/Interact.jl/blob/master/src/IJulia/setup.jl#L81
See https://github.com/JuliaGizmos/Interact.jl/pull/185#issuecomment-332066313

**Comment by rdeits** [comment]
I think the right thing is to give `setup.jl` its own module, which will totally isolate it from the user's namespace. I'm working on a PR for that now.
