### ISSUE TITLE
Interact does't working on Jupyterlab

### ISSUE THREAD

**Issue by Kelvyn88** [JuliaGizmos/Interact.jl#189]
Interact doesn't working on Jupyterlab. Could be great to try the new platform.

**Comment by JobJob** [comment]
It may be that it just doesn't work, but have you tried the solutions in #182 #183. What OS you on?

**Comment by Kelvyn88** [comment]
I think we need to wait for JupyterLab to reach a more stable version. Thanks for your response.

**Comment by korsbo** [comment]
I can confirm this issue. For me, Interact works with Jupyter but not Jupyterlab.

**Comment by Kelvyn88** [comment]
Any news related this issue? I want to start using Jupyterlab.

**Comment by piever** [comment]
Release version or master? Master should be working on Jupyter lab (at least it does on my machine).

Can you try 

```julia
Pkg.checkout("Interact")
Pkg.build("Interact")
cd(Pkg.dir("WebIO", "assets"))
;jupyter labextension install webio
;jupyter labextension enable webio/jupyterlab_entry
```

and see if it works on Jupyter Lab?

**Comment by piever** [comment]
Same as #205 , closing as those instructions seem to be sufficient to set it up on Jupyter Lab.

**Comment by vilim** [comment]
The new interact system looks great! Unfortunately, the above instructions hang at the point
```
Resolving packages...
julia-web-io@file:../extensions/julia-web-io-0.1.0-97b5f0b162b4023750034d7347
```
when trying to execute ;jupyter labextension install webio
I left it for ~20 min and it stays at the same state. I am using the current release of JupyterLab (0.32.1)

**Comment by piever** [comment]
Could you open an issue with all the details (package status of WebIO, in what folder you installed jupyterlab) over at WebIO? I would also recommend making sure you're on the latest release of WebIO, doing `Pkg.build("WebIO")` and trying again, as it may be that some things changed in WebIO recently and you need to rebuild it.
