### ISSUE TITLE
Slider being cleared with IJulia.clear_output(true)

### ISSUE THREAD

**Issue by rand5** [JuliaGizmos/Interact.jl#193]
I put together the following MWE for disappearing sliders.
Getting an issue when using Interact v0.6.2+ and Julia v0.6.1
Works fine on Interact v0.5.0 and Julia 0.6.0

```
A = slider(1:1:100)
display.([A])
foreach(signal(A)) do a
    IJulia.clear_output(true)
   println(a)
end
```

I think it is more an issue with the scope of `IJulia.clear_output(true)` than it is with the display of the results (e.g. [#182](https://github.com/JuliaGizmos/Interact.jl/issues/182)) since the following examples does work and, in the above MWE, you can see that the slider does momentarily appear before disappearing:

```
s = slider(1:10)
display(s)
signal(s)
```

**Comment by JobJob** [comment]
Interact.jl uses ipywidgets, and will whatever ipywidgets version you have installed (use Pkg.build("Interact") if you change ipywidgets versions). As of Ipywidgets v7.0.0 
"Widgets are now displayed in the output area ... calling clear_output() will delete the entire output, including the widget view" (from http://ipywidgets.readthedocs.io/en/stable/changelog.html)

I'm not sure of a good way to get around this in general in Interact.jl if you can't avoid calling `clear_output()`. If you can talk a little more about your use case their may be a suitable workaround.

**Comment by rand5** [comment]
My use case is that I have a data set and sliders that manipulate the data set in a given way. I would then like to be able to visualize the results. This means that I need a way to clear the previous plot every time a slider is adjusted (and display the new plot) while maintaining the ability to continue to adjust the slider. 

As an example:
```
using Interact
using PlotlyJS

A = slider(1:1:100,value=50,label="A");

display.([A])
foreach(signal(A)) do a
    IJulia.clear_output(true)
    x = rand(a)
    y = rand(a)
    
    trace1 = scatter(;x=x,y=y,mode="lines+markers")
    P1 = plot(trace1)
    display(P1)
end
```

**Comment by JobJob** [comment]
I do this with PlotlyJS

```
using Interact
using PlotlyJS

A = slider(1:1:100,value=50,label="A");
P1 = plot(1:10)
display.([A, P1])
foreach(signal(A)) do a
    x = rand(a)
    y = rand(a)
    
    trace1 = scatter(;x=x,y=y,mode="lines+markers")
    deletetraces!(P1, 1)
    addtraces!(P1, trace1)
end;
```

**Comment by JobJob** [comment]
Oh and also if your `x` values stay the same (unlike the above), instead of `addtraces!`, `deletetraces!` I just use `restyle!(P1, 1, y=[y])`. Note the nested `[y]` is (annoyingly) important. Also, obviously you'll want to set up the initial `P1 = plot(...)` to have the correct number of x values.

**Comment by rand5** [comment]
Thanks!

**Comment by rand5** [comment]
Is there a similar snappy solution for the Plots package?
My intuition has been incorrect:

```
using Interact
using Plots
pyplot()

A = slider(1:1:100,value=50,label="A");
display.([A])
P1 = plot()
foreach(signal(A)) do a

    empty!(P1.series_list)
    x = rand(a)
    y = rand(a)
    P1 = plot!(P1,x,y)
    
end
```

**Comment by rand5** [comment]
The following works, but seems a bit messy:

```
A = slider(1:1:100,value=50,label="A");
display.([A])

x = rand(A.value)
y = rand(A.value)
P1 = plot(x,y)

foreach(signal(A)) do a
    x = rand(a)
    y = rand(a)
    P1.series_list[1][:x] = x
    P1.series_list[1][:y] = y
    P1
end
```

**Comment by JobJob** [comment]
Does the first solution work if you change
```
display.([A])
P1 = plot()
```
to
```
P1 = plot()
display.([A,P1])
```
?

**Comment by rand5** [comment]
No, you get the same error about `P1` not being defined.

**Comment by JobJob** [comment]
You saw I switched the order of those two statements above right? This would be what I meant to try:
```
using Interact
using Plots
pyplot()

A = slider(1:1:100,value=50,label="A");
P1 = plot()
display.([A,P1])
foreach(signal(A)) do a

    empty!(P1.series_list)
    x = rand(a)
    y = rand(a)
    P1 = plot!(P1,x,y)
    
end
```

**Comment by rand5** [comment]
Yeah, I gave that a go.
The specific error is:

```
UndefVarError: P1 not defined

Stacktrace:
 [1] (::##117#118)(::Int64) at .\In[121]:6
 [2] map(::Function, ::Reactive.Signal{Int64}) at C:\Users\Cm7045\.julia\v0.6\Reactive\src\operators.jl:32
 [3] #foreach#37(::Array{Any,1}, ::Function, ::Function, ::Reactive.Signal{Int64}) at C:\Users\Cm7045\.julia\v0.6\Reactive\src\operators.jl:51
 [4] foreach(::Function, ::Reactive.Signal{Int64}) at C:\Users\Cm7045\.julia\v0.6\Reactive\src\operators.jl:51
 [5] include_string(::String, ::String) at .\loading.jl:515
```

**Comment by JobJob** [comment]
Try change this `P1 = plot!(P1,x,y)` to `plot!(P1, x, y)`

**Comment by JobJob** [comment]
Might need `withfig` too, see the pyplot section of https://github.com/JuliaGizmos/Interact.jl/blob/master/doc/notebooks/03-Interactive%20Diagrams%20and%20Plots.ipynb

**Comment by JobJob** [comment]
```
using Interact
using Plots
pyplot()

A = slider(1:1:100,value=50,label="A");
display.([A])
foreach(signal(A)) do a
    x = rand(a)
    y = rand(a)
    plot(x,y)
end
```

Works for me
