### ISSUE TITLE
Manipulate sliders hidden underneath output

### ISSUE THREAD

**Issue by cormullion** [JuliaGizmos/Interact.jl#196]
I need your help again guys! 

Interact and Luxor used to work happily together... For example, this used to work correctly (with some occasional glitches, https://github.com/JuliaGizmos/Interact.jl/issues/177) but now the sliders are drawn correctly but then hidden beneath the output. For example:

```
@manipulate for R in 1:10:200, r in 50:10:200, d in 1:200
    @png begin
        setline(0.2)
        hypotrochoid(R, r, d, :stroke)
        text("$R $r $d", 0, 150)
    end
end
```

draws the output correctly, but over the bars.

![screen shot 2017-11-26 at 10 39 55](https://user-images.githubusercontent.com/52289/33239278-314cf2b0-d296-11e7-853a-fc2c63089b84.png)

You can see that the sliders are drawn by inserting an error:

![screen shot 2017-11-26 at 10 41 27](https://user-images.githubusercontent.com/52289/33239285-660448fa-d296-11e7-8c2c-ae0f1998962d.png)

It's quite likely I've made a mistake somewhere in the IJulia code, but a clue or two would be great!

Is it related to https://github.com/JuliaGizmos/Interact.jl/issues/193?

Versions:

- Julia v0.6
- IJulia                        1.6.2
- Interact                      0.6.2
- Luxor                         0.10.1
- browsers Firefox and Safari on Mac.

**Comment by JobJob** [comment]
I can replicate, with Jupyter v5.x (help->about in the notebook) and IPywidgets v7.x (maybe `pip2 list | grep ipywidgets` or the same with pip3). Unfort I have no idea what's happening, and don't know when I'll get a chance to check it out - sorry.

> Is it related to #193?

Probably, but just in the sense that newer IPywidgets versions put the widgets in the same output area as everything else.

Vague ideas: is that png being sent in the right way? does jupyter offer some flag to avoid overwrite? can you replicate with just a standard png without using Luxor?

**Comment by cormullion** [comment]
@JobJob Thanks for the thoughts. There's a workaround, so I'll investigate it.
