### ISSUE TITLE
Install latest version of ipywidgets

### ISSUE THREAD

**Issue by dpsanders** [JuliaGizmos/Interact.jl#203]
Just had an experience trying to get Interact to work where the only solution was to manually do
```jl
Conda.rm("ipywidgets")
Conda.add("ipywidgets")
```
to install the latest version of `ipywidgets`, followed by `Pkg.build("IJulia")` and `Pkg.build("Interact")`.

It would be good to do this automatically. Not sure if this is the right place for the issue.

**Comment by piever** [comment]
Closing as latest (unreleased) Interact no longer relies on ipywidgets.
