### ISSUE TITLE
Add clarification that Interact works only in Jupyter notebook

### ISSUE THREAD

**Issue by dpsanders** [JuliaGizmos/Interact.jl#207]
A question on Slack showed that it isn't clear from the README that the package works *only* in the Jupyter notebook.

**Comment by piever** [comment]
Closing as latest (unreleased) Interact also works on Jupyter lab, Blink, Juno and in the browser, as detailed [here in the docs](https://juliagizmos.github.io/Interact.jl/latest/deploying.html).
