### ISSUE TITLE
How to use progress widget

### ISSUE THREAD

**Issue by utotch** [JuliaGizmos/Interact.jl#208]
In Interact.jl, it looks that progress (progress bar?) widget is implemented but I can't find any sample codes, and I don't understand how to use it although I read the source code.

Does anyone know how to use progress widget??

**Comment by JobJob** [comment]
It was broken a bit recently, so may not have worked even if it was clear how to use it 😄 

If you could test a branch with a fix or two - would be appreciated, from a julia prompt: 
```
Pkg.checkout("Interact", "jb/progress-nbwidgets")
Pkg.build("Interact")
```

Then to use it in jupyter/ijulia
```
using Interact

pbar = progress(range=-5.0:0.1:5.0)
display(pbar);
```
```
update!(pbar,-3.3)
```

**Comment by JobJob** [comment]
@utotch this work for you?

**Comment by JobJob** [comment]
Please re-open if not.

**Comment by utotch** [comment]
Hi @JobJob 
Thank you very much for commenting and sorry for late reply.
Unfortunately 
`Pkg.checkout("Interact", "jb/progress-nbwidgets")`
fails in my environment.

I can't recognize "jb/progress-nbwidgets" branch at https://github.com/JuliaGizmos/Interact.jl
and I think the reason for failure is missing the branch.
