### ISSUE TITLE
Checkbox is not reactively updated

### ISSUE THREAD

**Issue by cstjean** [JuliaGizmos/Interact.jl#211]
Unless I'm mistaken, this code should display a ticked checkbox, but the checkbox is unticked in IJulia

```julia
fx = Signal(true)
y = checkbox(value=false, signal=fx)
map(display, (y,fx))
push!(fx, true)
```

Updating works for `slider`

**Comment by JobJob** [comment]
Slider stays updated because of this code: https://github.com/JuliaGizmos/Interact.jl/blob/master/src/widgets.jl#L87-L96

You could (should! 😄) implement the same thing for checkbox.

**Comment by JobJob** [comment]
Should probably separate that functionality out into a function
```
function ensure_updated(w, sig)
    function keep_updated(val)
        if val != w.value
            w.value = val
            update_view(w)
        end
        nothing
    end
    preserve(map(keep_updated, sig; typ=Void))
end
```

Then you can just call that from slider, TextBox, and checkbox, and wherever else. The options is a little more complicated so we can leave that special cased

**Comment by JobJob** [comment]
I think we prob need the `init=nothing` see edit above.

No pressure of course, just if you feel like it. If not, I'll get around to making the change sometime soon I hope.

**Comment by JobJob** [comment]
np completely understand 👍

**Comment by piever** [comment]
This is fixed in the latest (unreleased) version of Interact, though the syntax has changed:

```julia
y = checkbox(value=false)
display(y)
observe(y)[] = true
```
