### ISSUE TITLE
UnicodeError in togglebuttons

### ISSUE THREAD

**Issue by rakhusur** [JuliaGizmos/Interact.jl#212]
When using unicode characters as keys for togglebuttons, I sometimes, but not always, get a UnicodeError.

In this code
```julia
using Interact

togglebuttons(Dict("a" => 2, "a⁻¹" => 2))
togglebuttons(Dict("a⁻¹" => 2))
```
the first line works, but the second doesn't:
```
UnicodeError: invalid character index 3 (0x81 is a continuation byte)
```

**Comment by piever** [comment]
This seems to work just fine in the new version of Interact (available via `Pkg.checkout("Interact")`). Feel free to reopen if after checking out the latest Interact you're still experiencing this issue.
