### ISSUE TITLE
show piracy

### ISSUE THREAD

**Issue by cstjean** [JuliaGizmos/Interact.jl#219]
In IJulia,
![image](https://user-images.githubusercontent.com/8622776/38579134-17f6dd14-3cd4-11e8-9938-9b74ccc183b3.png)

Shouldn't there be only one behavior?

**Comment by JobJob** [comment]
As you probably know, Interact enables the displayed value of Reactive signals to be automatically updated in the notebook.
```
using Reactive, Interact
s = Signal(10)
```
After `push!(s, 3)` the 10 will change to a 3 in the notebook.

So yeah, loading Interact enables this behaviour*. It's central to the way Interact works, and indeed, as you note, it modifies the behaviour of `show` for Signals in IJulia. The two packages are somewhat coupled, so yes it's piracy, but with consent (from JuliaGizmos). Is there a use case where you don't want that behaviour?

---
\* It works by setting up a map to send a message to the frontend when the signal's value changes here (which is called from `metadata(x::Signal)` [here](https://github.com/JuliaGizmos/Interact.jl/blob/95085776336fce518ae7f53c9758c1ddadf2ccba/src/IJulia/setup.jl#L93), which in turn is called when `display(s)` is called in IJulia): https://github.com/JuliaGizmos/Interact.jl/blob/95085776336fce518ae7f53c9758c1ddadf2ccba/src/IJulia/setup.jl#L77-L84 

and some js code here to handle receiving the message and redraw the value: https://github.com/JuliaGizmos/Interact.jl/blob/95085776336fce518ae7f53c9758c1ddadf2ccba/src/IJulia/ijulia.js#L48-L58

**Comment by cstjean** [comment]
Well, ok, I assume that the alternatives have been considered. Thank you for the detailed answer.

**Comment by cstjean** [comment]
3. Moving that code to Reactive.jl?

> Is it just a "right thing to do" thing

... I guess so? I spent ten minutes tracking down why my tests returned different results in a fresh Julia session. It's not the end of the world. I appreciate that there are competing concerns.

**Comment by shashi** [comment]
Maybe Reactive.jl can depend on WebIO to support this...
