### ISSUE TITLE
add `throttle` option to `@manipulate`

### ISSUE THREAD

**Issue by ssfrr** [JuliaGizmos/Interact.jl#225]
I was testing with the following code:

```julia
using Plots
using Interact
gr()

@manipulate for row in 1:100, col in 1:100
    data = zeros(100,100)
    data[row,col] = 1
    heatmap(data)
end
```

It's awesome that it was so easy to get it working. Unfortunately often the rendering can't keep up with all the signals being sent, so things get backed up and it makes the sliders jump erratically, and the plots flash quite a bit. Throttling the slider signals helps substantially, but then you can't just use `@manipulate` any more. Here's what I changed it to:

```julia
rowslider = slider(1:100)
colslider = slider(1:100)
display.([rowslider, colslider])
map(throttle(0.2, signal(rowslider)), throttle(0.2, signal(colslider))) do row, col
    data = zeros(100,100)
    data[row,col] = 1
    heatmap(data)
end
```

The plot still flashes a bit, but it's overall a smoother experience. It would be cool to have a `throttle` option, to handle this use-case. something like:

```julia
@manipulate for row in 1:100, col in 1:100, throttle=0.2
    data = zeros(100,100)
    data[row,col] = 1
    heatmap(data)
end
```

**Comment by piever** [comment]
I may try and implement something like this in [InteractBase](https://github.com/piever/InteractBase.jl) so I'm trying to understand what would be the preferred alternative behavior. I see to possible solutions:

1. `trottle` the signal (which I guess means only updating every `x` seconds?)

2. Update the signal "on release", meaning things get updated only when the slider gets released by the user

Which would you think would be more convenient?

**Comment by ssfrr** [comment]
For my usage throttling would be better. I want to be able to slide the slider back and forth and see the visualization update. The issue is just when the rendering process is slower than the rate at which the signal updates, so it gets backed up.

You can check the `throttle` implementation for details, but basically it should rate-limit the output by creating a refractory period after an update. The first update gets sent immediately, but then subsequent updates only get sent when the refractory period expires. So an example `Signal{Int}` sequence might look like this (with time running left-to-right):

```
input:   1   2  34  5              6 7 
output:  1    2    4    5          6    7
```

**Comment by piever** [comment]
Or even 

```julia
@manipulate for row in 1:100, col in 1:100
    data = zeros(100,100)
    data[row,col] = 1
    heatmap(data)
end throttle=0.2
```

Not really sure about the order.

**Comment by ssfrr** [comment]
My vote would be for one of the first two (with `throttle` at the top rather than after the `end`)

**Comment by shashi** [comment]
So (iirc) jupyter widgets do this by default: there are at most 3 outstanding updates at any given time. If a slider is too quickly moved, for example, only the last 3 items are kept in a buffer to be sent when the kernel is ready to receive them.

This of course requires an acknowledgement to be sent by the kernel for every update it receives.

**Comment by piever** [comment]
Added `throttle` option to `@manipulate` with the @ssfrr syntax (you may need to `Pkg.checkout("InteractBase")` for this to work):

```julia
@manipulate throttle=0.2 for row in 1:100, col in 1:100
    data = zeros(100,100)
    data[row,col] = 1
    heatmap(data)
end
```

**Comment by rand5** [comment]
Circling back to this- could the throttle behavior be expanded beyond the manipulate macro to sliders?
something like:
```
M = slider(1:1:10,label="M",value=1,throttle=0.5)
```
?

**Comment by rand5** [comment]
The use case is that if you have a slider with a very large range, for example
```
M = slider(1:1:1000,label="M",value=1)
```
But still need to be able to adjust it in small increments, the mouse inputs are not sensitive enough to do this. The workaround would be to select the slider, then press, but more specifically _press and hold_, an arrow key to do the finer adjustments, but this can cause the rendering of figures to backup as mentioned previously. This isn't solved by `onchange` since holding down an arrow key to adjust a slider by 10 units causes 10 calls to the widget.

**Comment by piever** [comment]
`throttle` is already available for any widget (but it would seem undocumented). The typical usage would be:

```julia
using Interact
s = slider(1:100)
throttled = throttle(0.5, s) # gets the "throttled value" of the observable
map(log, throttled)
```

It has a docstring but it has not been added to the Interact docs.
