### ISSUE TITLE
InteractBase.Widget: method error (was "Interact.slider: method error")

### ISSUE THREAD

**Issue by dav2017** [JuliaGizmos/Interact.jl#231]
Hi,

from 01-Introduction.ipynb I ran:
   xsquared = map(x -> x*x, Observable(s))
but it gives:
MethodError: no method matching *(::InteractBase.Widget{:slider,WebIO.Scope}, ::InteractBase.Widget{:slider,WebIO.Scope})

I am using Julia 6.3 and upgraded to latest versions of all packages (through Pkg.update() ) and the unreleased version of interact (obtained though: Pkg.checkout("Interact") ).

  Thanks for help,

   Davide

**Comment by piever** [comment]
You should be doing `xsquared = map(x -> x*x, observe(s))`: `observe` is the function to use to get an `Observable` from a widget that updates as soon as the user interacts with the widget. I couldn't fin `xsquared = map(x -> x*x, Observable(s))` in the new docs, from what I can see [here](https://github.com/JuliaGizmos/Interact.jl/blob/master/doc/notebooks/01-Introduction.ipynb) it says `xsquared = map(x -> x*x, observe(s))`.

**Comment by dav2017** [comment]
Thanks, my fault.

**Comment by piever** [comment]
Glad the new version is working out for you!
