### ISSUE TITLE
Rendering widgets consumes a lot of CPU

### ISSUE THREAD

**Issue by rdeits** [JuliaGizmos/Interact.jl#234]
There seems to be some *very* expensive rendering happening when Interact tried to display widgets. Just rendering a single slider like this: 

```julia
using Interact
widget(1:10)
```

in IJulia causes my browser to start consuming about 30-50% of a CPU core continuously. Rendering ~10 sliders consumes an entire CPU core and causes the browser to start locking up. I can reproduce this in both Firefox and Chrome on Ubuntu 18.04, using Interact master, InteractBase master, and WebIO master. 

~~This doesn't happen when I just use InteractBase instead of Interact.~~ Edit: not true, see below

Looking at the javascript profile shows an endless train of "recalculate style" calls: 

![screenshot from 2018-06-14 21-54-03](https://user-images.githubusercontent.com/591886/41446432-8d0c7c86-701d-11e8-8b9e-92255133ee83.png)

Can you reproduce this issue?

**Comment by rdeits** [comment]
Oh! It's not an issue with Interact vs. InteractBase; it's actually MathJax doing something. The high CPU usage does eventually end, and it corresponds to the `Processing math` and  `Typesetting math` messages popping up in the bottom-left corner. 

The following causes ~20 seconds of 100% CPU usage while MathJax does its thing: 

```julia
rx = slider(-π:0.01:π, label="rx")
ry = slider(-π:0.01:π, label="ry")
rz = slider(-π:0.01:π, label="rz")
x = slider(-1:0.01:1, label="x")
y = slider(-1:0.01:1, label="y")
z = slider(-1:0.01:1, label="z")
InteractBase.vbox(rx, ry, rz, x, y, z)
```

I'm still not sure *why* this is happening, though.

**Comment by rdeits** [comment]
Or maybe it's `katex` not `MathJax` that's the issue?

**Comment by shashi** [comment]
I think when any new output is shown in the notebook, MathJax renderer kicks in.

**Comment by piever** [comment]
I also don't think it's an Interact problem, as displaying widgets in Blink is quite responsive. Have you checked if UIkit has the same issue? You need to do `settheme!(:uikit)` to change css framework.

**Comment by piever** [comment]
Any idea how one can prevent MathJax from running in cell output?

**Comment by piever** [comment]
@rdeits thanks a lot for your detective work! It's actually quite easy to fix: if `ui` is your widget or layout of widgets, you can wrap it in `dom"div.tex2jax_ignore"` to stop MathJax madness. For example:

```julia
using WebIO, Interact

width, height = 700, 300
colors = ["black", "gray", "silver", "maroon", "red", "olive", "yellow", "green", "lime", "teal", "aqua", "navy", "blue", "purple", "fuchsia"]
color(i) = colors[i%length(colors)+1]
ui = @manipulate for nsamples in 1:200,
        sample_step in slider(0.01:0.01:1.0, value=0.1, label="sample step"),
        phase in slider(0:0.1:2pi, value=0.0, label="phase"),
        radii in 0.1:0.1:60
    cxs_unscaled = [i*sample_step + phase for i in 1:nsamples]
    cys = sin.(cxs_unscaled) .* height/3 .+ height/2
    cxs = cxs_unscaled .* width/4pi
    dom"svg:svg[width=$width, height=$height]"(
        (dom"svg:circle[cx=$(cxs[i]), cy=$(cys[i]), r=$radii, fill=$(color(i))]"()
            for i in 1:nsamples)...
    )
end
ui |> dom"div.tex2jax_ignore"
```

I'll change Interact so that widgets are wrapped in this thing by default.

**Comment by piever** [comment]
Should be fixed now, can you `Pkg.checkout("InteractBase")` and try again?
