### ISSUE TITLE
Master isn't working in Jupyter

### ISSUE THREAD

**Issue by Kelvyn88** [JuliaGizmos/Interact.jl#241]
I just did the checkout to the master branch. Now nothing is working in jupyter

**Comment by piever** [comment]
See [this comment](https://github.com/JuliaGizmos/Interact.jl/issues/189#issuecomment-405106983), I recommend updating your packages, `Pkg.build("WebIO")` and trying again. If that still doesn't work, please post your `Pkg.status()` and a clear description of the issue.

**Comment by piever** [comment]
There were several updates in WebIO which should make the installation more reliable, did this get fixed?
