### ISSUE TITLE
@manipulate doesn´t update the output

### ISSUE THREAD

**Issue by Kelvyn88** [JuliaGizmos/Interact.jl#244]
With the new release, the very basic example provided in the latest documentation isn´t working:

```julia
using Plots

x = y = 0:0.1:30

freqs = OrderedDict(zip(["pi/4", "π/2", "3π/4", "π"], [π/4, π/2, 3π/4, π]))

mp = @manipulate for freq1 in freqs, freq2 in slider(0.01:0.1:4π; label="freq2")
    y = @. sin(freq1*x) * sin(freq2*x)
    plot(x, y)
end
```

All the widget appears correctly, but if I move the slider of click on a button, the plot isn't updated. 

Kelvyn

**Comment by piever** [comment]
Somehow it looks as if the connection with Julia get lost when refreshing the page, but widgets are still displayed. Does it work if you simply open the notebook from scratch and try the demo (without refreshing or anything)?

**Comment by Kelvyn88** [comment]
Not working yet. I open the notebook and run the code... Widgets are displayed but don't update the plot.

Thanks

**Comment by piever** [comment]
I'm at JuliaCon, so I may be a bit slower in digging into this one.

Can you post your `Pkg.status()`? If you open your browser console, can you see any error?

If you try:

```julia
using Interact
wdg = slider(1:100)
vbox(wdg, observe(wdg))
```

And move the slider, do the values on the right and on the bottom of the slider update?

**Comment by Kelvyn88** [comment]
Now is working!! Thanks! Enjoy London

**Comment by xgdgsc** [comment]
If I run the code in second above comment , the value on the right updates, but not the bottom update, what could be the problem?

**Comment by xgdgsc** [comment]
Thanks. Seems working after I clear notebook widget state.

**Comment by tawheeler** [comment]
Ditto - had to run "cell -> all outputs -> clear" and then restart the notebook to resolve this issue.
