### ISSUE TITLE
labels with latex format not working

### ISSUE THREAD

**Issue by Kelvyn88** [JuliaGizmos/Interact.jl#245]
In jupyter, labels with latex format: L" ..." are nor working. 

Kelvyn

**Comment by piever** [comment]
For now you have to uss the [latex](https://juliagizmos.github.io/Interact.jl/latest/widgets.html#InteractBase.latex) function, e.g. `label = latex("\\sum_{i=1}^{\\infty} e^i")`, I'll see if there's an easy way to add support to latex strings.

**Comment by Kelvyn88** [comment]
Thanks!!!
