### ISSUE TITLE
Buttons now cut-off instead of moved to next row

### ISSUE THREAD

**Issue by djsegal** [JuliaGizmos/Interact.jl#248]
Pre-bulma, long button lists would be put on two lines.

Is there a way to add this behavior?

// right now overflow is being set to hidden :(

![screen shot 2018-08-15 at 3 09 36 am](https://user-images.githubusercontent.com/3156114/44136535-1fd765c4-a03b-11e8-98bb-ff50a96e6e95.png)

**Comment by piever** [comment]
Yes, definitely not good, thanks for reporting!

What would be the preferred behavior? Setting overflow to scroll or multiple line or leaving the user the choice?

I'll play a bit with the layout to see if I can find a solution that works reasonably for all cases.

**Comment by djsegal** [comment]
I'll try to make a PR for this soon! But you need to do a couple things:

+ Make more divs `max-width: 100%` in each button row
+ Stop using `full-width` class for buttons in flex grid
+ Use `flex-wrap: wrap` to use CSS for intelligent line breaks (please do not do this with code)

**Comment by piever** [comment]
Yes, I agree it's a matter of choosing the correct css classes and styles (and to see whether to use Bulma's classes or just flexbox - we should probably go with flexbox). In general layout is a bit of a weak spot of InteractBase, I'd definitely welcome PRs to improve things.

**Comment by djsegal** [comment]
Current attempt:

![screen shot 2018-08-15 at 9 38 06 pm](https://user-images.githubusercontent.com/3156114/44182143-98fc1100-a0d3-11e8-96db-0652e56002b1.png)

// see referenced PR just above this

**Comment by piever** [comment]
Fixed by https://github.com/piever/InteractBase.jl/pull/134
