### ISSUE TITLE
Handle booleans like strings

### ISSUE THREAD

**Issue by djsegal** [JuliaGizmos/Interact.jl#249]
Sorry to repeat:

+ https://github.com/piever/InteractBulma.jl/issues/18

But is there a way to support it? Not really a fan of toggle buttons or typing 100+ characters for `[true,false]`

-----

Can you point out where in the code it's converting that array into a slider?

**Comment by piever** [comment]
It's quite simple to fix this, there is a set of methods defined for the `widget` function and it's not always easy to choose the most appropriate, but I agree that a vector of booleans should definitely not be a slider by default...
