### ISSUE TITLE
Allow `@manipulate` to update sliders only when I "unclick"

### ISSUE THREAD

**Issue by Datseris** [JuliaGizmos/Interact.jl#262]
The `@manipulate` macro is very useful. I use with sliders.

When the computation is quite large, e.g. each update takes a second, having a slider can be problematic. Because if I slider a bit, `@manipulate` tries to do an update for _all_ values in the slider from end point until I unclick.

It would be great to allow `slider` and similar widgets to have an option that updates them _only_ when I unclick (that is, at the end point). From a user perspective the best API would simply be a keyword argument to slider and co..

**Comment by Datseris** [comment]
current workaround posted by Pietro: 

> If `s` is your slider, `on(x -> f(s[]), s[:changes])`

**Comment by piever** [comment]
To make sure I understand, would you want the displayed value (the one on the right of the slider) to update continuously or only when releasing the slider?

**Comment by piever** [comment]
Let me know if https://github.com/piever/InteractBase.jl/pull/113 fixes this for you!

**Comment by piever** [comment]
Fixed by https://github.com/piever/InteractBase.jl/pull/113
