### ISSUE TITLE
Why are there three projects instead of just one?

### ISSUE THREAD

**Issue by djsegal** [JuliaGizmos/Interact.jl#266]
First, what's the difference between Interact and InteractBase? 

1. What's an example of something that would have to go into Interact.jl?
2. What's an example of something that would have to go into InteractBase.jl?

Why is there even an InteractBulma? 

1. As there is only one css styling (:nativehtml being the exception), there doesn't seem to be a point?
2. Is there really a plan moving forward to add other css frameworks?

-----

The reason this is really an issue, though, is because it makes personal forks almost impossible. 

The three projects are updated together, rendering everything you develop alongside them broken within days, weeks, or months :/

**Comment by djsegal** [comment]
Maybe this shouldn't really be an issue.

// would be nice if there was a section in readme about how to help developing (or add a wiki page?)

**Comment by piever** [comment]
Interact at the moment is a meta package that reexports a bunch of useful things for web development. InteractBulma instead loads the css dependencies to get the Bulma style. There used to be a InteractUIkit to also use the UIkit css but it didn't seem to be worth the extra effort. Now the main alternative is between using Bulma or writing your own CSS code to add style to the classes that InteractBase gives you. So at the moment the package where the development actually takes place is InteractBase.
