### ISSUE TITLE
`PyPlot` plots not updated in `@manipulate`

### ISSUE THREAD

**Issue by dpsanders** [JuliaGizmos/Interact.jl#27]
`Interact.jl` is great, thanks!
But...

```
using Interact
using PyPlot

function g(N)
    PyPlot.plot(rand(N), rand(N), "o")
end

@manipulate for N in 1:100
    g(N)
end
```

gives a single plot that is not updated when the slider is moved.

However, executing another empty code cell shows all the other plots that were generated by the `@manipulate` command!

```
julia> versioninfo()
Julia Version 0.3.1-pre+17
Commit a3e7c04 (2014-08-25 18:52 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.0.0)
  CPU: Intel(R) Core(TM) i7-2677M CPU @ 1.80GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
```

**Comment by CARLOSMERCURY** [comment]
Hi, I have the same problem but using plot.implicit. 
This is my code

using SymPy, Interact
λ, x = symbols("λ,x", real=true);
 @manipulate for β=-1:0.1:1
        plot_implicit(x^3+β*x+λ^2-0.02,(λ, -2, 2),(x,-2, 2));
            end

I upload my code for 

f = figure()
@manipulate for ....; withfig(f) do
        .... plot routines go here ...

but Actually doesnt work. 

Thank you
