### ISSUE TITLE
using Interact mess up notebook menu items

### ISSUE THREAD

**Issue by xgdgsc** [JuliaGizmos/Interact.jl#277]
After running `using Interact` in jupyter notebook. The anchors in the menu items like Edit  -> Find and Replace (  `<a href="#"> Find and Replace </a>`  ) would change from `http://localhost:8888/MY_NOTEBOOK_PATH.ipynb#` to `http://localhost:8888/#` . Any following click on menu items would cause a disastrous redirect to root. 

I' m using 

```
julia> Pkg.installed()["Interact"]
v"0.9.0"
julia> Pkg.installed()["IJulia"]
v"1.14.1"

```

initially asked at https://github.com/JuliaLang/IJulia.jl/issues/780.

**Comment by piever** [comment]
I suspect it is related to https://github.com/JuliaGizmos/AssetRegistry.jl/issues/3, maybe worth asking over at AssetRegistry.

**Comment by shashi** [comment]
Which version of WebIO are you using?

**Comment by xgdgsc** [comment]
I don' t have WebIO installed before you ask. After installing WebIO v0.4.2 it still happens.

**Comment by xgdgsc** [comment]
It' s interesting it doesn' t happen after I find the theme missing toolbar missing and reset with `jt -r` and reenable with `jt -t monokai -f fira -fs 12 -T -N`.
