### ISSUE TITLE
WebIO not detected.

### ISSUE THREAD

**Issue by tamasgal** [JuliaGizmos/Interact.jl#280]
I can't get `Interact.jl` working, neither on my macOS (Mojave, with Julia 1.0.1 and Python 3.7), nor on my Arch Linux (Julia 1.0.1 and Python 3.7). I always get the error: `WebIO not detected.`
I have no problems with `Interact.jl` on juliabox.com, so it's not a browser issue.

Jupyter also works fine with Python 3 and Haskell notebooks (I am using this setup for many many years).

Any ideas how to debug this? I am not familiar with the mechanics of `Interact.jl` and `WebIO`.

![screenshot 2018-11-29 at 22 44 39](https://user-images.githubusercontent.com/1730350/49254173-d8533100-f428-11e8-9858-d26ca7ad0957.png)

**Comment by piever** [comment]
Can you do:

```julia
(v1.0) pkg> add WebIO@0.6.1
(v1.0) pkg> add InteractBase@0.8.1
```
just to make sure you're on the lastest release of WebIO? AFAIU on latest WebIO things should work fine and reasonably robustly in Jupyter Notebook but not yet in Jupyter Lab.

**Comment by tamasgal** [comment]
I did, but I get the same error. I am using Jupyter Notebook btw.

**Comment by tamasgal** [comment]
This is my `Pkg.status()`:

```
   Status `~/.julia/environments/v1.0/Project.toml`
  [7073ff75] IJulia v1.14.1
  [c601a237] Interact v0.9.0
  [d3863d7c] InteractBase v0.8.1
  [ee78f7c6] Makie v0.9.0
  [0f1e0344] WebIO v0.6.1
```

**Comment by piever** [comment]
The only thing that comes to my mind is checking the `deps/build.log` file (you have the full path in the first screenshot): I suspect that something went wrong with the build, in which case it'd be good to report at WebIO.jl

**Comment by tamasgal** [comment]
The `deps/build.log` is empty ;)

**Comment by tamasgal** [comment]
I just built it again but no output in `build.log`:

```
(v1.0) pkg> build WebIO
  Building WebIO → `~/.julia/packages/WebIO/NYISm/deps/build.log`

(v1.0) pkg>
```

**Comment by tamasgal** [comment]
Well, it's now working on ArchLinux (I rebuilt it again), but no luck on macOS. I filed an isse on the `WebIO.jl` issue board.

**Comment by piever** [comment]
Thank you, I'm closing here as WebIO is the correct place for the issue.
