### ISSUE TITLE
@manipulate slider value not updating

### ISSUE THREAD

**Issue by AshtonSBradley** [JuliaGizmos/Interact.jl#284]
```julia
@manipulate for n=1:10
    println("n=$n")
end
```
produces the initial output
```
n=5
```
but the slider value doesn't update when dragged:

![screen shot 2018-12-22 at 9 02 23 am](https://user-images.githubusercontent.com/24194258/50361409-5211b100-05c8-11e9-96cb-50c9eaa5fbaa.png)

so @manipulate doesn't seem to be updating any more

**Comment by AshtonSBradley** [comment]
running in `IJulia` with 
```julia
julia> versioninfo()
Julia Version 1.0.2
Commit d789231e99 (2018-11-08 20:11 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, broadwell)
Environment:
  JULIA_NUM_THREADS = 2
```

**Comment by dpsanders** [comment]
Which version of `Interact.jl` do you have installed?
I seem to remember there was a crucial change in version 0.10, so you may want to try

```
] add Interact@0.9.2
```
