### ISSUE TITLE
In Atom/Juno: HandlerFunction() not defined

### ISSUE THREAD

**Issue by Tilstandsrommet** [JuliaGizmos/Interact.jl#304]
I try 
```Julia
using Interact
@manipulate for n in 1:1000
            n
end
```
It works in a jupyter notebook, but not in Atom. I have all the atom-packages updated. It seems this is the function that fails in generic_http.jl:
```Julia
function WebIOServer(
        default_response::Function = (req)-> missing;
        baseurl::String = "127.0.0.1", http_port::Int = 8081,
        verbose = false, singleton = true,
        websocket_route = "/webio_websocket/",
        logger = devnull,
        server_kw_args...
    )
    # TODO test if actually still running, otherwise restart even if singleton
    if !singleton || !isassigned(singleton_instance)
        handler = HTTP.HandlerFunction() do req
            response = default_response(req)
            response !== missing && return response
            return serve_assets(req)
        end
        wshandler = WebSockets.WebsocketHandler() do req, sock
            req.target == websocket_route && websocket_handler(sock)
        end
        server = WebSockets.ServerWS(handler, wshandler, logger; server_kw_args...)
        server_task = with_logger(NullLogger()) do
            @async WebSockets.serve(server, baseurl, http_port, verbose)
        end
        singleton_instance[] = WebIOServer(server, server_task)
    end
    return singleton_instance[]
end
```

**Comment by versipellis** [comment]
Even just doing `ui = button()` as per the tutorial throws this.

**Comment by justacec** [comment]
Commenting here to track the changes, cause this is of course affecting me... (I was doing the ui = button() via the tutorial and lost an entire night thinking I was doing something wrong)

Using:
Atom 1.35.1 with
julia-client 0.8.2
language-julia 0.18.0
uber-juno 0.2.0

OSX 10.14.4

(v1.1) pkg> status
    Status `~/.julia/environments/v1.1/Project.toml`
  [c52e3926] Atom v0.8.4+ #master (https://github.com/JunoLab/Atom.jl.git)
  [ad839575] Blink v0.10.1
  [336ed68f] CSV v0.4.3
  [a93c6f00] DataFrames v0.17.1
  [31c24e10] Distributions v0.17.0
  [c91e804a] Gadfly v1.0.1
  [c601a237] Interact v0.10.2+ #master (https://github.com/JuliaGizmos/Interact.jl.git)
  [e5e0dc1b] Juno v0.7.0+ #master (https://github.com/JunoLab/Juno.jl.git)
  [91a5bcdd] Plots v0.24.0
  [f3b207a7] StatsPlots v0.10.2

**Comment by piever** [comment]
There were big changes in the underlying architecture Interact uses to render widgets. Should have been fixed by yesterday's WebIO release. Could you update and try again? Things should be working in Juno plot pane now.

**Comment by stords** [comment]
I am having this same problem in right now. Was there a solution found? Given that I just added Interact, I don't think that issue was resolved by the update.
