### ISSUE TITLE
two widgets for same observable. mutual updates

### ISSUE THREAD

**Issue by goretkin** [JuliaGizmos/Interact.jl#311]
Is there an example that allows both a textbox numeric entry and a slider to control an observable? Updating either widget would trigger an update in the other.

It might be more generic to allow two Observables to update each other, but I'm not sure how to avoid an infinite loop, without relying on other state, and possibly exposing race conditions.

**Comment by piever** [comment]
There is `rangepicker` for that (see [here](https://github.com/piever/InteractBase.jl/blob/master/src/slider.jl#L183)), for example `rangepicker(1:100, value = [10])`. Observables are allowed to update each other, to sync two observables and avoid infinite loop, you can either use a `Observables.ObservablePair` (source [here](https://github.com/JuliaGizmos/Observables.jl/blob/master/src/observablepair.jl#L1)) or the underlying machinery which is `setindex!(o, val; notify = t -> true)` (source [here](https://github.com/JuliaGizmos/Observables.jl/blob/master/src/Observables.jl#L80)) where the keyword `notify` determines which callbacks are triggered on updates.
