### ISSUE TITLE
Package compile interact is succeful but plots have no interactivity

### ISSUE THREAD

**Issue by ppalmes** [JuliaGizmos/Interact.jl#325]
Is there some steps to perform so that package compiling using PackageCompiler enables interactivity of the plots?

**Comment by travigd** [comment]
Do you have more context on what you're trying to do? What frontend are you using (Blink, Jupyter, Mux, etc.)?

Also, please make sure this issue is still present on the latest version of WebIO (0.8.7).

**Comment by ppalmes** [comment]
I am using Jupyter notebook, Julia 1.1, WebIO 0.8.6.

I'll try packagecompile with webio 0.8.7

**Comment by ppalmes** [comment]
tried with WebIO 0.8.8, still no interactivity with i use the slider. it seems that package compiling needs some ways to dynamically connect interact with webio... should i need init() function?

**Comment by YermolenkoIgor** [comment]
Has same problem. I tried to reinstall WebIO and Interact and build them. Then
```julia
using WebIO
jup = WebIO.find_jupyter_cmd()
WebIO.install_jupyter_nbextension( jup )
```
then create new notebook and interact examples startwd to work

**Comment by shashi** [comment]
@ranjanan has some experience with this.

**Comment by ranjanan** [comment]
Haven't tried interactive plots specifically but could you make sure that all everything WebIO and Interact depends on is getting linked (all the paths that the package depends on internally) correctly? That's a nice place to start.

**Comment by mdpetters** [comment]
I had a similar problem using ```Fezzik.jl``` with ```Interact.jl```. Running the WebIO setup function restored functionality for me. 

```julia
using WebIO
WebIO.setup(:ijulia)
```

**Comment by shashi** [comment]
Nice @mdpetters. If that was the problem then https://github.com/JuliaGizmos/WebIO.jl/pull/378 should fix this!
