### ISSUE TITLE
Allow Tuple in Manipulate

### ISSUE THREAD

**Issue by travigd** [JuliaGizmos/Interact.jl#328]
This is very important for me. :^)

We've talked about this before but I think it was in slack so it's lost to the slackhole (get it? i'm funny).

I want this syntax to work:
```julia
@manipulate for i in (1, 2, 3)
  # some computation based on choice of i
end
```

It should render discrete buttons (rather than a slider). I can try to do this myself too (code entrypoint would be a lot of help to get started!).

**Comment by piever** [comment]
It should actually be as simple as https://github.com/piever/Widgets.jl/pull/35, could you check whether that works for you?
