### ISSUE TITLE
Interaction with fps from Reactive.jl

### ISSUE THREAD

**Issue by stakaz** [JuliaGizmos/Interact.jl#346]
Hello, I am trying to do an animation of a simulation process and would like to have a time signal which updates the plot (beside other sliders). I am trying to reproduce examples from https://github.com/JuliaGizmos/Interact.jl/issues/36 but `timestamp` does not work anymore and I cannot figure out how to combine the `fps` from Reactive.jl and make it a trigger for the Widget.

Would be glad to see some hints.

Here is the code which does not work:

```julia
using Blink
using Compose, Reactive, Interact
anim = @manipulate for x=fps(10.0), color=["tomato", "bisque"], gravity=0:.1:2
	compose(context(0.5, 1-abs(sin(x[1]*gravity)), 0.1, 0.1), fill(color), circle())
end 

w = Window(async = false)
wdg = Widget(["anim" => anim])
body!(w, wdg);
```

I need the Blink package because I am using julia from within VS code and want a separate window with the animation.

Thanks.

**Comment by stakaz** [comment]
I found this notebook which can do what I want:
https://github.com/JuliaGizmos/Interact.jl/blob/master/doc/notebooks/04-Animations.ipynb

However, after the code is run for the first time there is the async job which never ends. Would it be possible to stop it once the Blink window is closed?

**Comment by travigd** [comment]
The latter (connection closed warning) is an issue with WebIO.

If you'd be willing to open an issue there, I'd be much obliged.
