### ISSUE TITLE
Error installing Jupyter nbextensions

### ISSUE THREAD

**Issue by sbacelar** [JuliaGizmos/Interact.jl#359]
I'm on `Windows 10` and using `Julia 1.4`. After doing `using WebIO` on the REPL if I do
`julia> WebIO.install_jupyter_nbextensions()`

I get:
```
ERROR: UndefVarError: install_jupyter_nbextensions not defined
Stacktrace:
 [1] getproperty(::Module, ::Symbol) at .\Base.jl:26
 [2] top-level scope at REPL[9]:1
```

**Comment by travigd** [comment]
There's no `s` at the end of it.

```
# For classic notebook
WebIO. install_jupyter_nbextension()

# For Jupyter Lab
WebIO.install_jupyter_labextension()
```

Did you copy that command from documentation somewhere or just mis-type? If the former, please let me know where so we can fix it. :^)
