### ISSUE TITLE
Question regarding ability to zoom

### ISSUE THREAD

**Issue by ChandlerKilpatrick1** [JuliaGizmos/Interact.jl#361]
I am trying to compare Makie and Interact and Makie has the ability to zoom in. Are you able to zoom in on a plot using Interact?

**Comment by amburosesekar** [comment]
using PlotlyJS with Interact, we got Real time interact and zooming Experience.

**Comment by travigd** [comment]
Yeah, it's mostly a function of the plotting backend. GR typically generates SVGs or PNGs, which aren't interactive in the browser (though SVG's can be zoomed in through the browsers zoom interface without getting pixelated).

This is almost completely related to Interact, unless you made `zoom` and Interact parameter:
```julia
@manipulate for zoom in 1:10
    plot(...; zoom=zoom)
end
```
But I'm not aware of any plotting backends that do that kind of thing.
