### ISSUE TITLE
Missing output of togglebuttons

### ISSUE THREAD

**Issue by babaq** [JuliaGizmos/Interact.jl#37]
i made togglebuttons based on the same options except previous togglebuttons selection.

``` julia
ff = ["F1","F2","F3","F4"]
f1 = togglebuttons(ff)
display(f1)
f2 = lift(x->togglebuttons(filter(a->a!=x,ff)),f1)
display(f2)
display(f1.signal)
display(f2.value.signal)
```

second togglebuttons could be correctly lifted whenever first togglebuttons was selected, but the order of togglebuttons  wasn't the same order of the filtered options.

Also, when first togglebuttons was selected to other than F1, the second togglebuttons could not give the F1 output.

![capture](https://cloud.githubusercontent.com/assets/92771/4243991/7bd6c6ae-3a18-11e4-865a-0e3203ffc4d2.PNG)

is there anything i am missing?

**Comment by JobJob** [comment]
This works on master:
```
using Interact
ff = ["F1","F2","F3","F4"]
f1 = togglebuttons(ff)
f1_inp = Signal("F2")
f2 = map(signal(f1)) do x
    togglebuttons(filter(a->a!=x, ff); signal=f1_inp)
end
display.([f1, f2, signal(f1), f1_inp]);
```

The ordering is a bug in ipywidgets, would be good if you can report it there, Python code:
```
from IPython.display import display
from ipywidgets import ToggleButtons
tb = ToggleButtons()
tb.options = [1,2,3]
display(tb)
tb.options = [0,1,2]
```
<img width="143" alt="screen shot 2016-12-11 at 2 37 28 am" src="https://cloud.githubusercontent.com/assets/854183/21074351/d89c08b8-bf4a-11e6-81b3-04565cf78498.png">

The order should be 0,1,2
