### ISSUE TITLE
Not installing in Julia 1.5.3

### ISSUE THREAD

**Issue by photor** [JuliaGizmos/Interact.jl#387]
(@v1.5) pkg> add Interact
 Installing known registries into `C:\Users\ytian\.julia`
      Added registry `General` to `C:\Users\ytian\.julia\registries\General`
  Resolving package versions...
......
   Building InteractBase → `C:\Users\ytian\.julia\packages\InteractBase\sOe2Z\deps\build.log`
┌ Error: Error building `InteractBase`:
│ ┌ Error: Download failed: curl: (35) schannel: failed to receive handshake, SSL/TLS connection failed
│ └ @ Base download.jl:43
│ ERROR: LoadError: failed process: Process(`'C:\WINDOWS\System32\curl.exe' -s -S -g -L -f -o 'C:\Users\ytian\.julia\packages\InteractBase\sOe2Z\assets\all.js' https://use.fontawesome.com/releases/v5.0.7/js/all.js`, ProcessExited(35)) [35]
│
│ Stacktrace:
│  [1] pipeline_error at .\process.jl:525 [inlined]
│  [2] download_curl(::String, ::String, ::String) at .\download.jl:44
│  [3] download(::String, ::String) at .\download.jl:62
│  [4] top-level scope at C:\Users\ytian\.julia\packages\InteractBase\sOe2Z\deps\build.jl:18
│  [5] include(::String) at .\client.jl:457
│  [6] top-level scope at none:5
│ in expression starting at C:\Users\ytian\.julia\packages\InteractBase\sOe2Z\deps\build.jl:17
└ @ Pkg.Operations C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.5\Pkg\src\Operations.jl:949
   Building Interact ────→ `C:\Users\ytian\.julia\packages\Interact\SbgIk\deps\build.log`

**Comment by photor** [comment]
I have tried many times, with the same error as above.

**Comment by travigd** [comment]
This is very often a firewall issue on windows. Can you try disabling it and seeing if it works?

**Comment by photor** [comment]
> 
> 
> This is very often a firewall issue on windows. Can you try disabling it and seeing if it works?

No, it still doesn't work after I disabled the windows firewall.

**Comment by photor** [comment]
Now it can be installed normally. Seems to be a temporary connection problem.
