### ISSUE TITLE
Improper Behavior When Not Using IJulia

### ISSUE THREAD

**Issue by TheCedarPrince** [JuliaGizmos/Interact.jl#388]
Thanks for creating a wonderful package JuliaGizmos team!

I am just opening a strange issue that I wanted to mention:

I actually initialize my Jupyter notebooks from a Python environment and then use a Julia kernel while working with my Julia-based Jupyter notebooks as I work with both Python and Julia. I find launching a notebook from a Python env, such as Conda, a bit more maintainable with package dependencies. Julia doesn't have any problems because their dependency ecosystem is great! 

I was trying to get widgets to return a value and could not despite the widgets appearing within my notebook. After some poking around, I realized I needed to have IJulia being used in the same notebook as Interact. This isn't really a bug so much as it is an interesting quirk when using Interact outside of an IJulia instance.

Is anyone able to reproduce this behavior? Would you be open to a Docs PR on this where I could make mention about it in the tutorial or troubleshooting section?

**Comment by travigd** [comment]
I'm confused by this.

If you're running a Julia kernel in Jupyter, you're using IJulia.

It is possible to use interact outside of IJulia (eg with Mux and Blink).

**Comment by travigd** [comment]
Try with the latest version of WebIO. You will probably need to install the `webio_jupyter_extension` Pip package in every (Python) environment where you launch the notebook.
