### ISSUE TITLE
Widgets not working accessing notebook server through ssh tunnel

### ISSUE THREAD

**Issue by jebej** [JuliaGizmos/Interact.jl#389]
If I run a notebook server on a remote computer, and access a notebook under ssh port forwarding, things mostly work, except for widget execution.

To be clear, the widgets themselves do appear, but if, e.g., I move a slider to modify a plot, the plot doesn't change. Things work when viewing the notebook locally.

I assume some communication is being blocked. How can I get this setup to work?

**Comment by travigd** [comment]
Try with the latest version of WebIO. Can re-open if you're still having issues.
