### ISSUE TITLE
Excruciatingly slow on Windows

### ISSUE THREAD

**Issue by henrikjaerleblad** [JuliaGizmos/Interact.jl#401]
I am using the Interact.jl package on Windows as a standalone web page via the webio_serve() function.
It is unfortunately really slow, taking approx 7s for every interactive action to take effect. Does anyone know if there is anything I can do to make it faster? 

I am also using it on Mac and there it works like a charm!

**Comment by travigd** [comment]
I don't have a Windows machine (nor, honestly, the time in the day) to try to figure this out. If you (or anyone) wants to try to profile this on Windows, I'd be open to that. Generally, with Windows performance issues, my first instinct is to check operations that interface with the filesystem.

Does turning off antivirus speed things up?

**Comment by henrikjaerleblad** [comment]
I think I found a solution. I had been using Julia 1.5.1, so I decided to remove Julia and all content in my .julia folder. I then installed Julia 1.6.2 and re-installed all my packages. I also allowed Julia freely through the firewall (which I am not certain I did before). And now, the response is almost instantaneous!

So I think it would be fine to close the issue now.
