### ISSUE TITLE
ERROR: UndefVarError: WEAVE_ARGS not defined

### ISSUE THREAD

**Issue by Stephen77777** [JuliaGizmos/Interact.jl#407]
I get the above error message whenever I try to execute:

SciMLTutorials.tutorial_footer(WEAVE_ARGS[:folder],WEAVE_ARGS[:file])

Can anyone help?

**Comment by travigd** [comment]
Interact.jl has nothing to do with SciMLTutorials (though maybe they use Interact). You'll need to address your issues with them.
