### ISSUE TITLE
@manipulate doesn't work with Ranges with negative strides

### ISSUE THREAD

**Issue by jiahao** [JuliaGizmos/Interact.jl#51]
``` jl
@manipulate for x=5:-1:-5
    x
end
```

The resulting widget displays but cannot be changed.

![screen shot 2015-02-21 at 7 57 50 pm](https://cloud.githubusercontent.com/assets/1732/6316890/f149c902-ba03-11e4-8aef-8b4363fbbc95.png)

**Comment by shashi** [comment]
it seems IPython's slider widget cannot handle negative steps.

**Comment by jiahao** [comment]
Perhaps the workaround on our end is to reverse the logic?

**Comment by shashi** [comment]
Yeah you mean the slider goes from -5 to 5? Or you could just use `-5:5` ;)

**Comment by jiahao** [comment]
Yes. Sometimes the input does naturally go in descending order though, like latitudes.

**Comment by jiahao** [comment]
Consider this example of a zoomable world map that I want to put into [World of Julia](https://github.com/jiahao/ijulia-notebooks/blob/master/2014-06-30-world-of-julia.ipynb):

```jl
using Compose, Interact, Shapefile

worldshapefile="ne_110m_admin_0_countries.shp"
isfile(worldshapefile) || dl("https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/110m_cultural/ne_110m_admin_0_countries.shp", worldshapefile)
worldshape = open(worldshapefile) do f
      read(f, Handle)
end
world=compose(context(), fill(nothing), stroke("black"), Polygons(worldshape.shapes)...)

@manipulate for limit_east=-180:180, limit_west=limit_east.value:180, limit_north=-90:90, limit_south=-90:limit_north.value
    left = limit_east
    right = limit_west
    up = limit_north
    down = limit_south
    box = UnitBox(left, up, right-left, down-up)
    compose(context(units=box), world)
end
```

In this example the inputs work but are rather unnatural.

**Comment by Carreau** [comment]
I would think this is even a limitation of html slider that can't be reversed.
I don't see any simple way to do that except using a minus_latitudes slider, but that would also feel weird.
